PKUHPC/OpenSCOW

- apps/job-server-slurm/src/config/env.ts
- apps/job-server-slurm/src/services/VncService.ts
- apps/portal-web/src/apis/api.mock.ts
- apps/portal-web/src/apis/api.ts
- apps/portal-web/src/pageComponents/desktop/DesktopTable.tsx
- apps/portal-web/src/pageComponents/desktop/DesktopTableActions.tsx
- apps/portal-web/src/pages/api/vnc/createDesktop.ts
- apps/portal-web/src/pages/api/vnc/killDesktop.ts
- apps/portal-web/src/pages/api/vnc/listDesktop.ts
- apps/portal-web/src/pages/apps/desktop.tsx
- protos/portal/vnc.proto
this pr fixes https://github.com/PKUHPC/SCOW/issues/6
> portal: allow multiple desktop sessions

- apps/mis-web/src/apis/api.mock.ts
- apps/mis-web/src/apis/index.ts
- apps/mis-web/src/components/JobBillingTable.tsx
- apps/mis-web/src/pageComponents/job/EditableJobBillingTable.tsx
- apps/mis-web/src/pages/api/job/getBillingTable.ts
- apps/mis-web/src/pages/dashboard.tsx
Fix the API error when no existing price item exists for a price item path.
> fix(mis-web): fix price table error when no item exists for a price item path

- apps/mis-web/src/pages/admin/jobBillingItems.tsx
- apps/mis-web/src/pages/admin/jobBillingTable.tsx
- apps/mis-web/src/pages/api/job/addBillingItem.ts
- apps/mis-web/src/pages/api/job/getBillingItems.ts
- apps/mis-web/src/pages/api/job/getBillingTable.ts
- protos/server/job.proto
Allow viewing and setting platform default price items.
> feat(mis): allow viewing and setting platform price items

- apps/portal-web/config/apps/vscode.yml
- docs/docs/portal/apps/configure-vnc-app.md
- docs/docs/portal/apps/configure-web-app.md
fix bug in interactive app document
> docs(portal): fix bug in interactive app doc

- apps/mis-server/src/services/account.ts
- apps/mis-server/src/services/admin.ts
- apps/mis-server/src/services/charging.ts
- apps/mis-server/src/services/init.ts
- apps/mis-server/src/services/job.ts
- apps/mis-server/src/services/jobChargeLimit.ts
- apps/mis-server/src/services/user.ts
add detailed gRPC error information
> chore(mis-server): add detailed error information

- apps/mis-server/src/services/user.ts
- apps/mis-server/tests/admin/user.test.ts
- apps/mis-server/tests/data/data.ts
- apps/mis-web/src/apis/api.mock.ts
- apps/mis-web/src/apis/api.ts
- apps/mis-web/src/layouts/routes/index.tsx
- apps/mis-web/src/pageComponents/admin/AllUsersTable.tsx
- apps/mis-web/src/pages/admin/users.tsx
- apps/mis-web/src/pages/api/admin/getAllUsers.ts
- protos/server/user.proto
show all users info in `/admin/users`
> feat(mis): show all users

- apps/mis-server/package.json
- apps/mis-server/tsgrpc.json
- apps/mis-web/package.json
- apps/mis-web/tsgrpc.json
- apps/portal-web/package.json
- apps/portal-web/tsgrpc.json
- pnpm-lock.yaml
Update tsgrpc to latest and update tsgrpc.json to latest schema
> chore: update tsgrpc to latest and update tsgrpc.json

- apps/mis-server/package.json
- apps/mis-web/package.json
- apps/portal-web/package.json
- pnpm-lock.yaml
tsgrpc just had a big update. try out if it works
> fix: update tsgrpc to latest

- apps/mis-web/src/apis/api.mock.ts
- apps/mis-web/src/apis/api.ts
- apps/mis-web/src/layouts/routes/index.tsx
- apps/mis-web/src/pageComponents/admin/TenantChargeForm.tsx
- apps/mis-web/src/pageComponents/admin/TenantPaymentTable.tsx
- apps/mis-web/src/pages/admin/finance/pay.tsx
- apps/mis-web/src/pages/admin/finance/payments.tsx
- apps/mis-web/src/pages/api/admin/finance/pay.ts
- apps/mis-web/src/pages/api/admin/finance/payments.ts
- apps/mis-web/src/pages/api/finance/getUsedPayTypes.ts
now platform finance can manage tenant finance info.
> add finance under platform admin

- apps/auth/tests/ssh.test.ts
- dev/docker-compose.dev.yml
- dev/ssh-server/Dockerfile
- dev/ssh-server/custom-cont-init.d/rsa.sh
- dev/ssh-server/entry.sh
fix #62
use alpine+openssh as ssh-server
> fix: login test-ssh-server as root

- docs/docs/common/dev.md
> docs: devenv

- apps/portal-server/src/services/app.ts
Fix app prop not properly returned in portal-server
> fix(portal-server): return app type properly

- .github/workflows/docs.yaml
- .github/workflows/test-build-publish.yaml
- apps/mis-server/__mocks__/undici.ts
- apps/mis-server/package.json
- apps/mis-server/src/services/user.ts
- apps/mis-server/tests/admin/user.test.ts
- apps/mis-server/tests/data/fetch.ts
- apps/mis-web/config.js
- apps/portal-server/package.json
- apps/portal-server/src/services/file.ts
- dockerfiles/Dockerfile.auth
- dockerfiles/Dockerfile.docs
- dockerfiles/Dockerfile.mis-server
- dockerfiles/Dockerfile.mis-web
- dockerfiles/Dockerfile.portal-server
- dockerfiles/Dockerfile.portal-web
- libs/auth/__mocks__/undici.ts
- libs/auth/package.json
- libs/auth/src/getCapabilities.ts
- libs/auth/src/validateToken.ts
- libs/auth/tests/validateToken.test.ts
- libs/auth/tsconfig.json
- package.json
- pnpm-lock.yaml
> feat: update to node 18

- apps/mis-server/scripts/slurm.sh
> fix: get cluster qos

- apps/portal-web/src/pageComponents/app/AppSessionsTable.tsx
> fix(portal-web): 修复修改集群时，已有应用表没有刷新的问题

- apps/mis-web/src/pageComponents/init/InitUsersAndAccountsTable.tsx
- apps/mis-web/src/pages/api/admin/setPlatformRole.ts
- apps/mis-web/src/pages/api/admin/setTenantRole.ts
- apps/mis-web/src/pages/api/admin/unsetPlatformRole.ts
- apps/mis-web/src/pages/api/admin/unsetTenantRole.ts
该pr修复了init时的bug，并对ui做了优化，使得在设置/取消用户角色期间，防止使用者重复操作表格。
> fix(mis): 修复了初始化管理用户界面的bug，使得为用户设置/取消角色功能能够正常使用

- apps/portal-server/src/services/file.ts
- apps/portal-server/tests/file/getFileMetadata.test.ts
- apps/portal-web/src/pages/api/file/download.ts
- protos/portal/file.proto
> feat(portal-web): 显示下载进度条

- apps/portal-server/src/services/job.ts
- apps/portal-web/src/pages/api/job/submitJob.ts
- protos/portal/job.proto
重构`SubmitJobResponse`结构以单独处理调度器提交出错的情况。
> refactor(portal): 重构`SubmitJobResponse`以单独处理调度器提交时出错的情况

- pnpm-lock.yaml
原来的Lock file里有一些npmmirror.com的信息（阿里的淘宝源），在本地电脑上删了lock file并重新安装依赖生成的lock file也有，但是我检查了一下我的本地电脑也没有任何地方配置使用了阿里源，很奇怪，所以在GitHub Workspaces开了个机器重新安装了一次，果然lock file就正常了？？
> chore: 在GitHub Workspace上重新创建lock file

- apps/gateway/nginx.conf
> fix(portal/apps):修复proxy转发时遗漏args问题，问题导致VSCode无高亮等

- apps/mis-web/src/pageComponents/init/InitUsersAndAccountsTable.tsx
> enhancement(mis-web): /init/users中用户和账户表放在tabs

- apps/mis-web/src/pageComponents/init/InitImportUsersTable.tsx
> feat(mis-web): 在初始化时提示用户只需要从一个集群中导入用户

- apps/mis-web/src/pageComponents/admin/ImportUsersTable.tsx
> refactor(mis-web): 优化导入用户的界面

- apps/portal-web/src/layouts/base/BaseLayout.tsx
- apps/portal-web/src/layouts/routes/index.tsx
> feat(portal-web): 登出后隐藏导航菜单

- .github/workflows/pr-lint.yaml
增加action以检查PR标题是否符合conventional commit标准。
> ci: 增加action以检查PR标题是否符合conventional commit标准

- LICENSE
- deploy/LICENSE
之前那个PR理解错了LICENSE文件的内容，应该是把整个授权协议的内容。
> docs: 更新LICENSE文件

- .github/workflows/pr-close-cleanup.yaml
- .github/workflows/scow-deployment.yaml
当PR关闭后，在scow-deployment仓库中删除对应的分支
> ci: 当PR关闭后，在scow-deployment仓库中删除对应的分支

- apps/portal-web/src/models/job.ts
- apps/portal-web/src/pageComponents/app/AppSessionsTable.tsx
- apps/portal-web/src/utils/appState.ts
目前排序方式是默认按照作业id排序，已结束任务也会排的比较靠前。现在优先把ENDED状态的作业排在最下方。
> fix(portal): 交互式应用作业列表把非ENDED状态排到最上方

- apps/mis-web/src/components/ClusterSelector.tsx
- apps/mis-web/src/layouts/base/header/DefaultClusterSelector.tsx
- apps/portal-web/src/components/ClusterSelector.tsx
- apps/portal-web/src/layouts/base/header/DefaultClusterSelector.tsx
> style(portal,mis): 优化默认集群选择框，增加提示

- apps/auth/src/auth/loginHtml.ts
- apps/mis-web/public/manifest.json
- apps/portal-web/public/manifest.json
- deploy/local/config-example/ui.yaml
- libs/config/src/ui.ts
> fix(web): 更新品牌主色

- libs/ssh/src/ssh.ts
1. 给`SshConnectError`增加添加`cause`的构造函数参数
2. `sshRawConnectByPassword`也throw `SshConnectError`
> fix(lib-ssh): 提高错误处理代码质量

- apps/portal-web/src/pages/api/proxy/[type]/[node]/[port]/[[...path]].ts
对于absolute代理模式，系统将会从URL解析出node和port信息后，把请求代理到`http://{node}:{port}/{请求原本的url}`。请求原本的url本来是从`req.url`中获取，但是系统有两种代理：HTTP代理和WebSocket代理，前者的`req.url`是经过next.js处理后的，去除了base path；后者是直接监听的Node.js原生`http.Server`对象的`upgrade`，这个事件的参数中的`req.url`并没有去掉base path。#347 统一给HTTP和WS的absolute类型的代理添加了BASE_PATH，使得websocket代理后的地址有了两个base path。此PR解决了这个问题。
> fix(portal-web): 修复ws代理对absolute代理模式的URL添加多余的base path的问题

- .github/workflows/test-build-publish.yaml
- dockerfiles/Dockerfile.docs
- docs/nginx.conf
> ci: 修复和构建文档镜像

- apps/mis-web/config.js
- apps/mis-web/src/utils/config.ts
- apps/portal-web/config.js
- apps/portal-web/src/pages/api/auth/index.ts
- apps/portal-web/src/pages/api/proxy/[type]/[node]/[port]/[[...path]].ts
- apps/portal-web/src/utils/config.ts
- deploy/local/generate.py
- libs/web/src/routes/auth/redirectToLogin.ts
支持部署认证系统在不同的域名下。同时重新设计几个base path相关的设置。
需要重新拉取scow-deployment。
> feat(web): 支持认证系统在不同的域名下

- deploy/local/README.md
- deploy/vagrant/README.md
在部署项目的README中增加将部署项目相关的问题提交到SCOW项目的说明，以及给scow-vagrant项目增加授权说明。
> docs: 部署项目增加README

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .vscode/extensions.json
- docs/docs/contribution/dev.md
https://code.visualstudio.com/docs/devcontainers/containers
> feat: 增加Dev Container配置

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/playwright.yml
- .vscode/extensions.json
- e2e/.gitignore
- e2e/README.md
- e2e/package.json
- e2e/playwright.config.ts
- e2e/tests-examples/demo-todo-app.spec.ts
- e2e/tests/example.spec.ts
- e2e/tests/login.spec.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
使用[playwright](https://playwright.dev/)增加e2e测试的配置。增加一个简单的登录测试。
当前e2e测试依赖vagrant集群环境，还不能自动运行。
> feat(e2e): 增加e2e测试基础代码

- apps/mis-web/src/layouts/routes.tsx
> feat(mis): 移除layout中的获取作业tab

- apps/mis-web/src/layouts/BaseLayout.tsx
> feat(mis): 移除mis系统的默认集群选择框

- .changeset/perfect-dragons-serve.md
- apps/mis-server/config/priceItems.json
- apps/mis-server/src/bl/PriceMap.ts
- apps/mis-server/src/bl/jobPrice.ts
- apps/mis-server/src/plugins/price.ts
- apps/mis-server/src/services/init.ts
- apps/mis-server/src/services/job.ts
- apps/mis-server/src/tasks/fetch.ts
- apps/mis-server/tests/job/billingItems.test.ts
- apps/mis-web/src/apis/api.mock.ts
- apps/mis-web/src/apis/api.ts
- apps/mis-web/src/pageComponents/init/InitLayout.tsx
- apps/mis-web/src/pages/api/job/getMissingDefaultPriceItems.ts
- protos/server/job.proto
当系统遇到一个数据库中不存在计费项的作业时，系统获取作业将会报错。为了避免这个情况发生，这个PR加入了以下检查机制：
- mis-server启动时将会自动检查当时的默认计费项是否完整覆盖了集群中所有的计费项。如果不完整，将会打log
- mis完成初始化时，系统将会检查默认计费项是否完整覆盖了集群中所有的计费项。如果没有，系统将不会允许完成初始化
- 
这个PR同时整理了一下计算作业费用相关的代码。
> feat(mis): 检查默认作业计费项是否完整

- deploy/local/config-example/clusters/hpc01.yaml
- deploy/vagrant/scow/scow-deployment/config/clusters/hpc01.yaml
- dev/vagrant/config/clusters/hpc01.yaml
- docs/docs/deploy/config/cluster-config.md
- docs/docs/deploy/config/multi-cluster/index.md
- docs/docs/deploy/get-started/vagrant/customization.md
- libs/config/src/cluster.ts
> feat: 集群配置文件无需配置计算节点

- .changeset/twenty-bees-fly.md
- apps/portal-server/src/clusterops/api/job.ts
- apps/portal-server/src/clusterops/slurm/bl/submitJob.ts
- apps/portal-server/src/clusterops/slurm/job.ts
- apps/portal-server/src/services/job.ts
- apps/portal-web/src/apis/api.mock.ts
- apps/portal-web/src/apis/api.ts
- apps/portal-web/src/pageComponents/job/JobTemplateTable.tsx
- apps/portal-web/src/pages/api/job/getJobTemplate.ts
- apps/portal-web/src/pages/api/job/listJobTemplates.ts
- apps/portal-web/src/pages/jobs/savedJobs.tsx
- apps/portal-web/src/pages/jobs/submit.tsx
- protos/portal/job.proto
把代码中所有关于作业模板的代码的英文从saved job改成job template，包括组件名、proto中gRPC API定义、HTTP API定义等
> fix(portal): 把代码中 SavedJobs 字样全部改为 JobTemplate

- .changeset/quiet-scissors-explain.md
- apps/mis-server/src/services/job.ts
- apps/mis-server/tests/job/JobService.test.ts
- protos/server/job.proto
管理系统GetJobs API增加start_bi_job_index参数，用于获取从某一个bi_job_index开始的作业信息。
> feat(mis): GetJobs API增加start_bi_job_index参数

- .github/workflows/test-build-publish.yaml
修复ifaxity/wait-on-action修改分支带来的问题
> fix(ci): 修改ifaxity/wait-on-action分支

- .changeset/eight-stingrays-knock.md
- apps/cli/package.json
- apps/cli/src/cmd/checkConfig.ts
- apps/cli/src/cmd/generate.ts
- apps/cli/src/cmd/init.ts
- apps/cli/src/cmd/migrate.ts
- apps/cli/src/cmd/updateCli.ts
- apps/cli/src/cmd/viewInstall.ts
- apps/cli/src/compose/cmd.ts
- apps/cli/src/config/env.ts
- apps/cli/src/config/install.ts
- apps/cli/src/config/proxy.ts
- docs/docs/deploy/install/scow-cli.md
- pnpm-lock.yaml
将CLI也改为pino logger，和系统其他部分统一，并默认显示日志等级，方便查看
> feat(cli): 使用pino Logger

- .changeset/warm-glasses-glow.md
- apps/cli/assets/fluent/fluent.conf
- apps/cli/assets/install.yaml
- apps/cli/src/cmd/init.ts
- apps/cli/tests/init.test.ts
- apps/cli/tests/utils.ts
在使用CLI初始化配置文件时，将fluent的配置文件放到目录下fluent/fluent.conf下。
> fix(cli): CLI初始化时增加fluent配置文件

- .changeset/poor-icons-boil.md
- apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
- apps/portal-web/src/pages/api/job/submitJob.ts
- protos/portal/job.proto
使SubmitJobRequest的`partition`参数为必填。
> refactor(api): 提交作业必须指定分区

- .changeset/nine-seals-refuse.md
- apps/mis-server/src/services/user.ts
- apps/mis-web/src/apis/api.mock.ts
- protos/server/user.proto
> fix(mis): 账户下的用户列表接口 response 增加 email 字段

- apps/portal-web/src/pages/api/shell/index.ts
有时候Shell长时间不用会断开，可能的原因是系统前面的代理（例如nginx）会自动断开长时间不交换信息的连接。
本PR使portal-web中的shell后端每30s ping一次所有客户端，手动发一条消息。
浏览器端的WebSocket不支持发送ping消息，故在WebSocket服务器端发送ping消息。
> fix(portal-web): Shell后端定时给ping所有客户端，防止Shell连接断开

- .changeset/gentle-emus-admire.md
- docs/docs/deploy/get-started/vagrant/index.md
> fix(docs): 补充vagrant初始化部署

- .github/workflows/test-build-publish.yaml
似乎是github actions bug： https://github.com/orgs/community/discussions/61819 。
暂时取消CI过程中的测试步骤
> fix(ci): 暂时取消CI测试

- .changeset/old-ads-bathe.md
修复changeset文件中的拼写错误，原因是没有自动生成changeset文件, 导致`patch`拼写错误
> fix(changeset): changeset文件中拼写错误

- .github/workflows/test-build-publish.yaml
- dev/docker-compose.dev.yml
原来不是bug，是因为ssh-server的配置不对。修改后测试即正常。
> ci: 恢复CI测试

- .changeset/modern-phones-crash.md
- apps/mis-web/src/pages/dashboard.tsx
> fix(mis-web): 解决开发环境下 mis-web 进入 dashboard 页面报错的问题

- .changeset/fuzzy-snails-sin.md
- docs/docs/integration/scow-api-hook/api.md
- docs/docs/integration/scow-api-hook/proto.md
完善audit-server使用scow api与外部系统交互的文档部分。
> docs(audit):  增加 SCOW API 中 audit-server 部分的文档

- .changeset/forty-owls-buy.md
- apps/mis-web/src/models/operationLog.ts
- libs/operation-log/src/index.ts
修复两个bug
1. 操作日志里 修改作业时限时，详情展示 时间为NAN, 参数错误。
2. 创建操作日志时，then改为catch。
> fix(lib-operation-log): 修改作业时限操作日志内容展示修复及创建操作日志错误捕获 bug 修复

- .changeset/thirty-geckos-grin.md
> chore: 增加1.0发布changeset

- apps/audit-server/package.json
- apps/mis-server/package.json
- apps/mis-web/package.json
- apps/portal-server/package.json
- apps/portal-web/package.json
- dev/test-adapter/package.json
- libs/hook/package.json
- libs/operation-log/package.json
- libs/protos/scheduler-adapter/package.json
- libs/protos/scow/package.json
- libs/rich-error-model/package.json
- libs/scheduler-adapter/package.json
- libs/server/package.json
- libs/web/package.json
- pnpm-lock.yaml
- renovate.json
> fix: 启用@grpc/grpc-js更新

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/config.yaml
- .github/ISSUE_TEMPLATE/feature-request.yaml
> feat: 添加issue模板

- .changeset/seven-glasses-rest.md
修改安全漏洞修复 pr https://github.com/PKUHPC/SCOW/pull/1004 的 changeset 文件
> chore: #1004修改变更版本

- docs/docs/deploy/config/ai/intro.md
增加SCOW AI Beta期间使用SCOW AI的配置文件指引
> docs: 增加SCOW AI Beta期间使用SCOW AI的配置文件指引

- .changeset/chilled-cougars-protect.md
- apps/mis-web/src/pages/admin/monitor/resourceStatus.tsx
> feat(mis-web): 调整监控 iframe 高度自适应

- .changeset/heavy-flies-repair.md
- apps/auth/src/routes/changeEmail.ts
- apps/auth/src/routes/changePassword.ts
- apps/auth/src/routes/checkPassword.ts
- apps/auth/src/routes/createUser.ts
- apps/auth/src/routes/getUser.ts
- apps/mis-server/src/services/user.ts
- apps/mis-web/src/i18n/en.ts
- apps/mis-web/src/i18n/zh_cn.ts
- apps/mis-web/src/pageComponents/profile/ChangeEmailModal.tsx
- apps/mis-web/src/pageComponents/profile/ChangePasswordModal.tsx
- apps/mis-web/src/pages/admin/tenants/create.tsx
- apps/mis-web/src/pages/api/admin/changePassword.ts
- apps/mis-web/src/pages/api/profile/changeEmail.ts
- apps/mis-web/src/pages/api/profile/changePassword.ts
- apps/mis-web/src/pages/api/profile/checkPassword.ts
- apps/mis-web/src/pages/api/tenant/changePassword.ts
- apps/mis-web/src/pages/api/tenant/create.ts
- apps/portal-web/src/i18n/en.ts
- apps/portal-web/src/i18n/zh_cn.ts
- apps/portal-web/src/pageComponents/profile/ChangePasswordModal.tsx
- apps/portal-web/src/pages/api/profile/changePassword.ts
- apps/portal-web/src/pages/api/profile/checkPassword.ts
> fix: 使用外部认证系统时，外部系统未实现的功能在用户使用时提示用户功能未实现

- .changeset/eight-forks-sneeze.md
- apps/mis-web/src/i18n/en.ts
- apps/mis-web/src/i18n/zh_cn.ts
- apps/mis-web/src/pages/user/partitions.tsx
> feat(mis-web): 集群和分区信息数据异步请求页面优化

- .changeset/little-apricots-mix.md
- apps/portal-web/src/pages/dashboard.tsx
> fix(portal-web): 仪表盘cpu和gpu利用率百分比显示错误

- apps/audit-server/src/services/statistic.ts
- apps/mis-server/src/services/charging.ts
- apps/mis-server/src/services/job.ts
- apps/mis-server/src/services/user.ts
- libs/server/src/date.ts
checktTimeZone -> checkTimeZone
> style: 修复拼写错误 

- .changeset/little-snakes-camp.md
- apps/ai/config/ai/apps/jupter.yaml
- apps/ai/src/server/trpc/route/jobs/apps.ts
- dev/vagrant/config/ai/apps/jupyter.yaml
- docs/docs/deploy/config/ai/apps/apps/jupyterlab/index.md
jupyter应用启动时，PasswordIdentityProvider.hashed_password不生效，改为ServerApp.password
> fix(ai):  修复jupyter启动时参数错误问题

- .github/workflows/api-breaking.yaml
- package.json
- protos/server/job_charge_limit.proto
根package.json增加`pnpm api:breaking`命令，可检查api的破坏性更新。并增加一个workflow，专门用于检查破坏性更新。
> ci: PR增加API breaking change检查

- .github/workflows/api-breaking.yaml
- .github/workflows/docs-preview.yaml
- .github/workflows/docs.yaml
- .github/workflows/lint-pr-content.yaml
- .github/workflows/pr-cleanup.yaml
- .github/workflows/side-projects.yaml
- .github/workflows/tag-release.yaml
- .github/workflows/test-build-publish.yaml
1. 可以通过仓库的ACTION_RUNNER_LABEL设置修改ci的运行actions的runner
2. 修复tag-release没有正常运行的问题
> ci: 修复一些问题

- .changeset/thirty-avocados-dance.md
- apps/ai/src/server/utils/copyFile.ts
> fix: ai的cp命令

- apps/ai/src/i18n/en.ts
- apps/ai/src/i18n/zh_cn.ts
- apps/mis-web/src/pageComponents/job/ChangeJobTimeLimitModal.tsx
- apps/portal-web/src/i18n/en.ts
- apps/portal-web/src/i18n/zh_cn.ts
- apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
> 主要是portal的提交作业页面优化。
1. 原脚本输出文件UI部分清除，原功能转移至左下角保存作业提交文件；
2. 不选中单选框则不显示路径且不保存，选中则显示路径且保存；
3. 默认路径文件名从固定的job%j.script变更为作业名.sh。当作业名改变时，此处跟随变化。
1. 增加小时和天的选项与管理系统的修改作业时限统一；
2. 优化UI与上下行对齐且中小屏幕下英文模式宽度不足时不强求对齐，该列相对上下行变宽；
3. 要求填写精确到整数位。
1. 要求填写精确到整数位。
> fix(portal/mis): 提交作业页面优化

- docs/docusaurus.config.ts
- docs/package.json
- pnpm-lock.yaml
使用 https://github.com/easyops-cn/docusaurus-search-local 作为文档的搜索引擎，对中文效果更好。
> fix(docs): 更换文档搜索引擎

- .changeset/tasty-files-end.md
- apps/ai/src/server/trpc/route/jobs/apps.ts
- apps/ai/src/server/trpc/route/jobs/jobs.ts
- apps/portal-server/src/clusterops/app.ts
- apps/portal-server/src/services/job.ts
- apps/portal-web/src/pageComponents/app/LaunchAppForm.tsx
- apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
- apps/portal-web/src/pages/api/app/createAppSession.ts
- apps/portal-web/src/pages/api/job/submitJob.ts
> revert: "fix: ai和hpc在提交作业和应用前检查一下是否重名"

- .changeset/strange-lemons-notice.md
- apps/ai/src/app/clientLayout.tsx
> Revert "feat: ai加上国际化的Provider"

- .changeset/strange-lemons-notice.md
- apps/ai/src/app/clientLayout.tsx
- apps/ai/src/server/setup/jobShell.ts
- apps/ai/src/server/trpc/route/jobs/apps.ts
> fix: jobShell connect container

- .changeset/giant-drinks-remain.md
- docs/docs/integration/ui-extension/develop.md
- libs/web/src/extensions/ExtensionPage.tsx
- libs/web/src/extensions/events.ts
> feat(web): UI扩展支持修改页面标题

- .changeset/tidy-pianos-reply.md
- apps/ai/src/app/(auth)/jobs/[clusterId]/LaunchAppForm.tsx
- apps/ai/src/server/trpc/route/jobs/jobs.ts
> feat(ai): TensorFlow框架增加psNode和workerNode参数

- docs/docs/hpccluster/basic-config.md
- docs/docs/hpccluster/nfs.md
- docs/docs/hpccluster/slurm.md
1. using hostname
2. random mysql password
> docs(docs): 使用hostname 以及环境变量 增强文档安全性

- .changeset/heavy-frogs-unite.md
- apps/mis-server/src/services/job.ts
作业费用更改时，如果为充值，充值记录的 comment 中记录作业的 user 属性，这样查账或统计账单时可以更加精确
> fix(mis-server): 作业费用更改时，如果费用减少需要充值，充值记录的 comment 中记录作业的 user 属性

- apps/auth/src/auth/ssh/index.ts
close https://github.com/PKUHPC/SCOW/issues/1426
> fix(auth): provide a default value for full name

- .github/workflows/api-breaking.yaml
- .github/workflows/docs-preview.yaml
- .github/workflows/docs.yaml
- .github/workflows/lint-pr-content.yaml
- .github/workflows/pr-cleanup.yaml
- .github/workflows/side-projects.yaml
- .github/workflows/tag-release.yaml
- .github/workflows/test-build-publish.yaml
修改CI脚本为外来贡献者做准备
- 去掉所有variables
> ci: 为外来贡献者做准备

- .github/workflows/side-projects.yaml
- .github/workflows/test-build-publish.yaml
- 来自fork的PR不更新vagrant仓库
- build images push到fork的来源仓库
> ci: 使得CI可以给来自外部作者的fork仓库发起的PR运行

- .changeset/doc-fix.md
- README.md
> fix: 更新OpenSCOW的README.md文件
