apps/portal-web/package.json
dockerfiles/Dockerfile.auth
dockerfiles/Dockerfile.clusterops-slurm
dockerfiles/Dockerfile.docs
dockerfiles/Dockerfile.job-server-slurm
dockerfiles/Dockerfile.mis-server
dockerfiles/Dockerfile.mis-web
dockerfiles/Dockerfile.portal-web

Improve dockerfiles
- Avoid `pnpm fetch` and install dependencies independently for each container so that each container only installs needed dependencies
- Using `corepack` to sync pnpm version
- portal-web build can cache to git clone novnc. Code change no longer causes git clone to rerun

Improve dockerfile

---

apps/auth/src/config/auth.ts
apps/mis-server/src/tasks/fetch.ts
apps/mis-server/src/utils/parse.ts
docs/docs/common/auth/ldap.md
docs/docs/portal/apps/configure-web-app.md
docs/docs/portal/deployment.md
libs/config/src/appConfig/mis.ts
libs/config/src/appConfig/portal.ts
libs/config/src/parse.ts
libs/config/tests/parse.test.ts

Change the template format from `{a}` to `{{ a }}` to align with most template engines and make it easier to distinguish template part of a string.
This is a BREAKING CHANGE with existing configs. Please update the configs in the following config keys:
- config/auth.yml: `ldap.addUser.homeDir`, `ldap.addUser.extraProps`
- config/mis.yaml: `jobChargeComment`
- config/portal.yaml: `submitJobDefaultPwd`
- config/app/{app}.yml: `web.connect`

refactor: Changing template format from {a} to {{ a }}

---

apps/mis-server/src/services/init.ts
apps/mis-server/tests/init/init.test.ts
apps/mis-web/src/apis/api.mock.ts
apps/mis-web/src/apis/api.ts
apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
apps/mis-web/src/pages/api/init/createInitAdmin.ts
apps/mis-web/src/pages/init.tsx
apps/mis-web/tsconfig.json
protos/server/init.proto

Assign users with tenant_admin role when creating init admin users. Also rename APIs and pages to avoid confusion.

fix(mis): assign initial user with tenant_admin role

---

apps/mis-server/config/clusters/hpc00.yml
apps/mis-server/config/mis.yaml
apps/mis-server/scripts/slurm.sh
apps/mis-server/src/clusterops/slurm/utils/slurm.ts
docs/docs/mis/schedulers/slurm.md
libs/config/src/appConfig/cluster.ts
libs/config/src/appConfig/mis.ts

The slurm script needs the name of the table `associationTableName` containing user association information. Most users don't care about the db structure created by slurm. Actually, the value is generated by slurm with format `{cluster name}_assoc_table` where the `cluster name` is set by user. 
This PR replaces `associationTableName` config key to `clusterName` config key so that the user don't have to know the table name, but only need the cluster name in slurm.
This is a BREAKING change. Current deployed SCOW needs the following steps to migrate to the latest version
- Replace the `slurm.sh` with the latest version
- In the `clusters/{cluster}.yaml` files, replace the `associationTableName` config with `clusterName` and set the values to the name in slurm

feat(mis)!: replace assoc table name with slurm cluster name config

---

apps/auth/config/ui.yaml
apps/auth/src/config/ui.ts
apps/mis-server/src/config/mis.ts
apps/mis-server/src/tasks/createBillingItems.ts
apps/mis-web/config.js
apps/mis-web/src/pages/user/partitions.tsx
apps/mis-web/src/utils/config.ts
apps/portal-web/config.js
libs/config/src/appConfig/clusterTexts.ts
libs/config/src/appConfig/mis.ts
libs/config/src/appConfig/portal.ts
libs/config/src/appConfig/ui.ts
libs/config/src/fileConfig.ts
libs/config/tests/fileConfig.test.ts

Simplify config design.
- Consistent schema type naming. All schema types are the same as their respective schema object.
- All file configs have a function to get config file. Greatly simplifies importing.
- Disallow optional config. All config files are required to exists

feat: simplify config design

---

apps/mis-server/src/entities/JobInfo.ts
apps/mis-server/src/plugins/price.ts
apps/mis-server/src/tasks/fetch.ts
apps/mis-server/src/utils/constants.ts
apps/mis-server/tests/job/JobService.test.ts
apps/mis-server/tests/job/billingItems.test.ts
apps/mis-server/tests/job/fetchJobs.test.ts
apps/mis-server/tests/job/testData.json

Don't throw when source jobs contain users and accounts that do not exist in scow db. For those jobs, the tenant is "", the account and tenant prices are both zero, and the job price item id is UNKNOWN.

feat(mis): don't throw when user or account is not found in source jobs

---

apps/portal-web/config/apps/vscode.yml
apps/portal-web/src/clusterops/slurm/app.ts
apps/portal-web/src/clusterops/slurm/bl/submitJob.ts
docs/docs/portal/apps/configure-vnc-app.md
docs/docs/portal/apps/configure-web-app.md
libs/config/src/appConfig/app.ts

Manager can add extra slurm params when submitting an interactive job.
Add an option named `slurm.options` in `config/apps/app1.yml`
```yml
id: emacs
name: emacs
type: vnc
slurm:
options:
- "-X node[1-2]"
vnc: 
xstartup: |
emacs -mm
```

add extra slurm params when running interactive apps

---

apps/auth/tests/ssh.test.ts
apps/portal-web/README.md
apps/portal-web/config.js
apps/portal-web/config/clusters/hpc02.yaml
apps/portal-web/env/.env.test
apps/portal-web/src/pages/api/file/getHome.ts
apps/portal-web/src/pages/files/[cluster]/[[...path]].tsx
apps/portal-web/tests/file/utils.ts
dev/docker-compose.dev.yml
docs/docs/refs/env/portal-web.md

Different clusters might have different homedir path for the same user. This PR
- redirects to home dir when cluster is changed, and
- use the homedir path for the cluster
This PR also changes the test ssh server to use the same username as the host os username instead of "test".

fix(portal): allow different homedir paths for the same user on different clusters

---

apps/portal-web/src/pageComponents/filemanager/FileManager.tsx
apps/portal-web/src/pages/api/file/copy.ts
apps/portal-web/src/pages/api/file/move.ts
apps/portal-web/tests/file/copy.test.ts
apps/portal-web/tests/file/mv.test.ts

Add error messages when copy or move fails. Error messages only prompts out when copying or moving one file.

feat(portal): add error messages when copy or move fails

---

apps/portal-web/package.json
libs/auth/package.json
libs/auth/src/validateToken.ts
libs/ssh/package.json
libs/ssh/src/key.ts
libs/ssh/src/ssh.ts
pnpm-lock.yaml

Currently, if some lib functions require logger, the lib must add `pino` as its dependency even though the lib only needs its types. 
The dependency to the exact version of the exact package is not necessary, and also breaks build if pino in the library is upgraded, but some other libraries that requires pino (like `tsgrpc-server`)  hasn't upgraded to the new version of pino (example: https://github.com/PKUHPC/SCOW/actions/runs/3222132273/jobs/5270871414).
This PR introduces [ts-log](https://github.com/kallaspriit/ts-log) as a common interface for logger. The logger users (e.g. lib functions) only depends on the `Logger` instance, and don't require dependency on the actual `pino`.

feat: use ts-log for log interface abstraction

---

apps/mis-web/src/pageComponents/tenant/AdminUserTable.tsx
apps/mis-web/src/pages/tenant/users/list.tsx

This PR makes the following changes to the /tenant/users/list screen of the management system.
1. Passing user information to the AdminUserTable component.
2. Added two columns to the AdminUserTable to enable the setting/removal of the tenant administrator and tenant treasurer roles.

feat(mis): set up/remove tenant roles on the front-end of tenant/list

---

apps/portal-web/assets/slurm/server_entry.sh

bug: get_password function returns "password" instead of a random string.

fix bug: get_password function returns "password"

---

apps/mis-web/config.js
apps/mis-web/src/pageComponents/users/CreateUserForm.tsx
apps/mis-web/src/pages/api/init/createInitAdmin.ts
apps/mis-web/src/pages/api/tenant/createAccount.ts
apps/mis-web/src/pages/api/users/create.ts
apps/mis-web/src/pages/tenant/accounts/create.tsx
apps/mis-web/src/utils/config.ts
docs/docs/mis/deployment.md
libs/config/src/appConfig/mis.ts

Allow to customize user id using `userIdPattern` config in `mis.yaml` like account name.
Notice that this PR removes default user id rule. To use the previously default rule, use `^[a-z0-9_]+$` as `userIdPattern.regex`.
Add a new property `userIdPattern` in mis.yaml to specify the regex and error message for user id values.

feat(mis): allow to customize user id pattern

---

.github/workflows/test-build-publish.yaml

阿里云镜像库极度不稳定，而且速度相比GitHub CR没有明显优势。在CI中去除上传到阿里云镜像库。之后入股有需求的话，使用一些镜像库同步工具，把镜像从GHCR同步到国内镜像中去。

ci: 去除上传到阿里云镜像

---

apps/portal-web/src/pageComponents/desktop/DesktopTable.tsx

是个比较傻的bug。原来的代码中，DesktopTable组件刷新时，会根据当前querystring的cluster现场构建一个cluster类型对象。每次cluster对象是不一样的，但是创建新的clusdter对象又会触发一次新的查询，刷新一次组件。这样就会进入一个死循环。

fix(portal-web): 修复桌面列表选择集群死循环

---

apps/portal-server/config/apps/vscode.yml
apps/portal-server/src/services/app.ts
apps/portal-web/config/apps/vscode.yml
apps/portal-web/src/apis/api.mock.ts
apps/portal-web/src/pageComponents/app/ConnectToAppLink.tsx
apps/portal-web/src/pages/api/app/connectToApp.ts
docs/docs/portal/apps/configure-jupyter-app.md
docs/docs/portal/apps/configure-vscode-app.md
docs/docs/portal/apps/configure-web-app.md
libs/config/src/app.ts
protos/portal/app.proto

在交互式应用的配置文件中，在web配置子项指定proxyType，取值为relative和absolute。当type为vnc时，proxyType不设置

fix(portal): 交互式应用配置文件proxyType移动到web配置子项

---

apps/mis-web/src/pages/api/profile/changePassword.ts
apps/portal-web/src/pages/api/profile/changePassword.ts
libs/auth/src/changePassword.ts
libs/auth/src/index.ts
libs/auth/tests/changePassword.test.ts

此次PR在libs/auth/src下实现了changePassword的api接口，并在libs/auth下的test中使用mock添加了对该方法的测试。最终将mis/portal-web中对changePassword的调用改为了使用该封装好的接口。

feat(libs): 在lib-auth中实现了修改密码的api的接口，并在web端调用

---

apps/gateway/nginx.conf

当前，对于Jupyter等交互式应用，如果配置了BASE_PATH，nginx反向代理发送到后端计算节点的uri不正确，没有考虑到包括BASE_PATH的完整路径. 比如访问`https://hpc.pku.edu/scow_base_path/proxy/192.168.220.133/7383/index.html`, `/proxy/192.168.220.133/7383/index.html`会被发送到计算节点，这是一个不完整的路径。
PR解决了这个问题，现在` /scow_base_path/proxy/192.168.220.133/7383/index.html` 会被发送到计算节点。

fix(portal): 修复配置BASE_PATH的话jupyter无法连接问题

---

.github/workflows/test-build-publish.yaml
libs/ssh/src/ssh.ts
libs/ssh/tests/sshKey.test.ts

之前我们假设创建用户后，以用户身份第一次登录后，系统会自动创建用户的家目录并配置bash的一些参数。我们也同时在此时给新的用户配置免密登录的文件。但是目前发现在一些集群中，即使以新用户登录后，系统仍然不会创建家目录，此时原来的逻辑将会报错。
此PR处理了这一情况，当以新用户登录后发现用户家目录不存在，则调用insertKeyAsRoot来配置免密登录。

fix(ssh): 创建用户时，如果以用户身份登录后用户家目录仍不存在，使用insertKeyAsRoot配置免密登录

---

apps/portal-web/src/layouts/routes/index.tsx
apps/portal-web/src/pageComponents/job/SavedJobsTable.tsx
apps/portal-web/src/pages/jobs/savedJobs.tsx

在提交作业页面的选项为“保存为模板”，已保存的作业的即为模板，这里将命名修改，使得命名统一。另外去掉了“提交时间”的column。

fix(portal): 修改了"已保存作业"界面ui的一些命名并去掉“提交时间”的column

---

apps/mis-server/src/entities/User.ts

之前使用@property注解中的type：arraytype表示user实体中的成员tenant_role和platform_role。现在使用@enum注解

refactor(mis-server): 使用enum array表示tenant_role和platform_role

---

dockerfiles/Dockerfile.auth
dockerfiles/Dockerfile.docs
dockerfiles/Dockerfile.mis-server
dockerfiles/Dockerfile.mis-web
dockerfiles/Dockerfile.portal-server
dockerfiles/Dockerfile.portal-web

之前，每个镜像在构建的时候都只下载自己的组件所需要的依赖（例如组件A需要a, b包，组件B需要a, c包）。这固然减少了每个镜像下载依赖的大小（每个组件只下载自己所需要的依赖，A不会下载c，B不会下载a），但是构建系统时需要同时构建所有镜像，每个镜像所需要的依赖不一样，那么docker就会同时对每个组件下载自己的依赖，会同时产生大量网络请求（同时有组件A下载a, b，组件B下载a, c四个请求），如果此时用户的网络条件不好，或者使用了有资源限制的代理服务器，那么就可能下载出错。
pnpm有一个`fetch`子命令（ https://pnpm.io/cli/fetch ），它只需要lock文件（整个项目只有一个lock文件），运行此命令可以把lock文件中的所有依赖先全部下载下来。这样，预先下载好所有镜像后，后面的pnpm install过程就不需要发起任何网络请求了。
通过此功能，整个系统在构建的时候只需要下载一次依赖（整个系统的所有依赖，例子中的a, b, c），下载依赖后，各个镜像在后续就不会发起下载依赖的网络请求，提高了整个系统的构建速度。

refactor: 在dockerfile中使用pnpm fetch

---

apps/mis-web/package.json
apps/portal-web/package.json
pnpm-lock.yaml

之前使用next.js 13.0.3时，所有带有querystring的请求都失败了，检查了一下发现URL中分割pathname和querystring的?符号不存在。回退到13.0.2后正常。先回退到13.0.2，之后再检查到底是哪儿的问题。

fix(web): 回退next.js到13.0.2以解决fetch时URL中不能带querystring的问题

---

dev/docker-compose.dev.yml
dev/ldap/Dockerfile

在openeuler下，centos7容器的默认open files值是1073741816，在build阶段安装glibc的时候，以及启动容器的时候会报错，需要把open files改小

fix: 修复某些开发环境中ldaptest容器openfiles bug

---

apps/mis-web/src/pageComponents/admin/ImportUsersTable.tsx

之前用户和账户表格放在一个页面，现在放在tabs中，方便查看

enhancement(mis-web): 导入用户的用户和账户表格改成Tab

---

apps/mis-server/src/services/admin.ts
apps/mis-server/src/utils/slurm.ts
apps/mis-server/tests/admin/getClusterUsers.test.ts
apps/mis-web/src/apis/api.mock.ts
apps/mis-web/src/pageComponents/admin/ImportUsersTable.tsx
apps/mis-web/src/pages/api/admin/importUsers.ts
protos/server/admin.proto

在导入用户的表格中, 用checkbox显示已经在scow系统中的用户和账户, 使用者不能操作checkbox, 系统默认导入所有不存在scow中的用户和账户.
持久化入数据库的逻辑不变, 也就是说后端假设新导入的用户和账户与原来scow中存在的用户与账户没有任何依赖关系.

enhancement(mis): 导入用户和账户时显示已经存在的用户和账户

---

apps/mis-web/package.json
apps/portal-web/package.json
pnpm-lock.yaml
renovate.json

next 13.0.4仍然存在 #279 的问题。仍然退回13.0.2，并忽略next的更新。

fix(web): rollback next to 13.0.2 and ignore next update for now

---

apps/gateway/nginx.conf

之前的正则表达式会将rest中以数字开头的识别为port，导致整个转发失败。

fix(portal/apps): proxy中location的正则表达式识别错误

---

.github/workflows/test-build-publish.yaml

之后将会公开的demo集群部署在/demo/scow下，需要单独构建镜像。使用GitHub Actions自动构建demo集群所需要的镜像。

ci: 增加demo集群的镜像

---

apps/portal-web/src/pageComponents/desktop/DesktopTable.tsx
apps/portal-web/src/pageComponents/desktop/NewDesktopTableModal.tsx
apps/portal-web/src/pages/desktop/index.tsx

1. 增加刷新按钮
2. 将创建桌面放到搜索区域中
3. 创建桌面时默认使用选中的集群，不单独选择集群

feat(portal-web): 更新登录节点桌面UI设计

---

apps/mis-web/src/layouts/base/BaseLayout.tsx
apps/mis-web/src/layouts/base/SideNav/index.tsx
apps/mis-web/src/utils/head.tsx
apps/portal-web/src/layouts/base/BaseLayout.tsx
apps/portal-web/src/layouts/base/SideNav/index.tsx
apps/portal-web/src/pageComponents/dashboard/CustomizableLogoAndText.tsx
apps/portal-web/src/pageComponents/shell/Shell.tsx
apps/portal-web/src/pages/shell/[cluster]/[[...path]].tsx
apps/portal-web/src/utils/head.tsx

1. 去除内容一直出现的底部的滚动条，只有宽度过宽会出现滚动条
1. 修复Shell无法正常全屏的问题
3. Shell可以正常放大缩小 
4. 门户主页logo最大宽度为设备宽度
5. 去除侧边栏滑出时的底色（见下图，现在已经没有了）
6. 修复title标签有多个组件的报错

fix(web): 修复一些UI细节问题

---

apps/mis-web/src/layouts/base/header/index.tsx
apps/portal-web/src/layouts/base/header/index.tsx

例如base path是`/demo/scow`，管理系统部署在`/mis`下，那么之前门户系统header中的跳转到管理系统的link的href实际上是`/demo/scow/demo/scow/mis`。这是因为之前使用Link组件，而Link组件将会在已经有了base path的MIS_URL变量的基础上再加一个base path。这个PR修复了这个问题。

fix(web): 修复base path不为/的时候，header中门户和管理系统的Link指向不正确的问题

---

apps/auth/package.json
apps/mis-server/src/plugins/orm.ts
dockerfiles/Dockerfile.auth
dockerfiles/Dockerfile.mis-server
dockerfiles/Dockerfile.portal-server
package.json

之前五个node镜像中，有的镜像的项目代码在`src`中，有的在`build`中；有的使用ENTRYPOINT作为dockerfile的启动语句，有的使用CMD。这个PR统一了这些区别。
1. 所有镜像中的项目代码均存放在`build`中
2. 所有Dockerfile均使用`CMD ["npm", "run", "serve"]`作为容器的启动语句
同时还修改了根目录下的build:containers命令改成了build:images

chore: 统一镜像结构

---

apps/portal-server/src/clusterops/slurm/app.ts
apps/portal-server/src/services/app.ts

在需要启动或者连接应用的时候，动态加载交互式应用的配置文件。修改交互式应用的配置文件后，不需要重启服务，就可以在创建应用时立即生效。

fix(portal): 动态加载交互式应用的配置文件

---

libs/auth/src/index.ts

位于/libs/auth/src的getUser函数未在index.ts中导出，这里进行导出

fix(lib-auth): 将lib/auth/src下的getUser在index.ts中进行export导出

---

deploy/config-example.py
dev/.env.build

config.py中的COMMON.IMAGE_BASE和IMAGE_TAG需要和构建时的dev/.dev.build中指定的IMAGE_BASE和IMAGE_TAG对应。我发现目前默认的构建时的tag为latest，但是默认的config.py中为master，不匹配。
Fixes #325

fix(build): 修改默认构建的镜像的TAG为master

---

libs/libconfig/src/fileConfig.ts
libs/libconfig/src/validation.ts
libs/libconfig/tests/fileConfig.test.ts
libs/libconfig/tests/global.d.ts

```
Error: Error reading config file /home/ddadaal/Code/scow/libs/libconfig/tests/configFileTestundefined/test.yaml: data/loaded must be string
```

feat(lib-config): 在配置文件格式不正确抛出的错误信息中增加配置文件路径

---

.github/workflows/lint-pr-content.yaml
.github/workflows/test-build-publish.yaml
apps/portal-server/tests/file/exists.test.ts
apps/portal-web/src/pageComponents/filemanager/FileManager.tsx
apps/portal-web/src/pages/api/file/fileExist.ts
apps/portal-web/src/pages/api/file/getFileType.ts

#327 没有lint代码就提交了，后面发现是因为之前只在commit的时候使用git的pre-commit hook使用eslint检查代码风格，但是这个步骤可能会被人跳过。这次在CI的时候检查代码风格，这样就绕不过了。同时修复 #327 的代码格式问题。

ci: CI步骤增加代码格式检查

---

package.json
pnpm-lock.yaml

项目有lint protos文件（lint:protos）和lint ts代码（lint:ts）两个命令。这两个命令实际上可以并行运行。引入`concurrently`包，使得在根目录下运行`pnpm lint`时可以并行运行两个lint命令，减少lint的运行时间。

chore: 引入concurrently并行运行lint命令

---

apps/mis-web/src/layouts/darkMode.tsx
apps/mis-web/src/utils/hooks.ts
apps/portal-web/src/layouts/darkMode.tsx
apps/portal-web/src/utils/hooks.ts

在localStorage中增加一个`scow-dark-mode`的设置，记住用户黑暗模式的设置，这样用户刷新或者切换到门户/管理系统时黑暗模式设置不会重置为系统。

fix(web): 在localStorage中记住用户黑暗模式的设置

---

apps/portal-server/src/services/shell.ts

在通过ssh创建shell的时候，默认使用的终端为`vt100`，只支持16色，所以有的时候颜色显示不全。现在把使用的终端程序改成`xterm-256color`，能够显示更多颜色。

fix(portal-server): 使用xterm-256color创建shell

---

apps/portal-web/src/utils/route.ts

https://github.com/PKUHPC/SCOW/commit/00481d45e39d2ce794cdafcdc097d755103ecf61 这个commit新引入了一种通过metadata传递SCOW业务错误代码的方式，但是在前端判断是否为SCOW业务逻辑的代码有问题。Metadata.get返回的一定为数组，一定为真值，于是前端会把所有grpc错误都认为为SCOW业务逻辑错误。这个PR修复了这个问题。

fix(portal-web): 修复从metadata中判断是否为SCOW业务逻辑错误的逻辑

---

apps/portal-server/src/utils/turbovnc.ts
apps/portal-server/tests/utils/parseVncOutput.test.ts

之前如果启动桌面或者桌面类应用时displayId大于等于10，那么解析出来的displayId只包括第一个数字对应的数字。比如displayId是21，但是解析出来只能解析出2。这个PR解决了这个问题

fix(portal-server): 解决VNC桌面和应用启动时displayId大于等于10后，解析displayId不正确的问题。

---

package.json
pnpm-lock.yaml
scripts/lintProtos.mjs

我们使用protolint来lint proto文件，为了让用户不需要单独安装protolint的二进制文件，我们通过`docker run`用protolint的docker镜像来执行protolint。在用docker执行的时候使用`-v $(pwd):/workspace`把当前目录映射进容器中，`$(pwd)`在powershell和bash中都支持，但是npm默认用cmd.exe来执行npm script，我们不能简单地修改npm的`script-shell`配置来配置npm使用什么shell来执行script中的脚本，因为可能有的依赖的script依赖了npm的默认行为（即在windows下使用cmd.exe）。所以我们引入了zx，并手动处理了windows和*nix两种情况下路径应该怎么传入，从而实现了在windows下和*nix下都可以执行lint protos命令。

fix: 修复lint protos的脚本在windows下无法执行的问题

---

package.json
pnpm-lock.yaml
scripts/lintProtos.mjs

#358 使用zx来执行lint protos文件的命令，结果zx自带的escape规则会使得当参数中存在有中文字符的时候，参数前面会被自动加上一个$，而且似乎没有办法可以绕过这个规则。zx对非POSIX系统的支持也不佳，#358中用了多处workaround才绕过了在windows下的一些坑。SCOW项目将一直支持Windows开发环境，而zx的这些问题使得使用zx的坑多于带来的好处。所以这个PR去掉了zx，直接使用最原始的child_process来运行命令。

fix: 使用child_process执行lint protos文件的命令

---

docs/src/pages/index.tsx

fix(docs): 首页标题去掉Hello from SCOW，改为SCOW

---

apps/mis-server/src/utils/slurm.ts
apps/mis-server/tests/admin/getClusterUsers.test.ts

导入用户功能需要首先获取集群中已有的用户，获取已有用户是通过`slurm.sh -l all`获取的。这个命令在发现一个没有用户的账户时会有以下输出，之前没有处理。修复后，获取已有用户账户时会忽略没有用户的账户。
```
a_t2
There is no user in account !
```

fix(mis-server): 修复导入用户功能在获取集群中已有用户时，有账户没有用户的情况时报错的问题

---

apps/mis-server/scripts/slurm.sh
apps/mis-server/src/clusterops/slurm/utils/slurm.ts
deploy/local/config-example/clusters/hpc01.yaml
docs/docs/deploy/SCOW/mis/schedulers/slurm.md
libs/config/src/mis.ts

增加集群配置文件中的`slurm.mis.dbUser`和`slurm.mis.slurmAcctDbName`配置，用于指定slurm accouting数据库的用户名和数据库名。

feat(mis-server): 允许自定义slurm.sh连接数据库的用户名和数据库名

---

dockerfiles/Dockerfile.auth
dockerfiles/Dockerfile.docs
dockerfiles/Dockerfile.mis-server
dockerfiles/Dockerfile.mis-web
dockerfiles/Dockerfile.portal-server
dockerfiles/Dockerfile.portal-web
libs/auth/tsconfig.json
libs/config/tsconfig.json
libs/decimal/tsconfig.json
libs/libconfig/tsconfig.json
libs/protos/tsconfig.json
libs/ssh/tsconfig.json
libs/tsconfig.json
libs/utils/tsconfig.json
libs/web/src/layouts/base/header/components.tsx
libs/web/src/layouts/icon.tsx
libs/web/src/utils/throttle.ts
libs/web/tsconfig.json
scripts/copyDist.mjs
tsconfig.json

现在在VSCode中按住ctrl再点击引用能够正确跳转到源码了，之前只能跳转到生成的.d.ts文件。
原理是tsconfig的declarationMap选项（https://www.typescriptlang.org/tsconfig#declarationMap）。
这个选项将会在build目录下创建一些.ts.map文件，生产时并不需要，所以同时修改了copyDist.mjs脚本，把map中的.ts和.ts.map文件删掉，以减小最终镜像的大小
另外还在libs下放了一个公共的tsconfig.json，开启了declaration和declarationMap选项。

fix(dev): 启用tsc的declarationMap选项，整理libs下的tsconfig文件

---

apps/portal-server/src/clusterops/slurm/app.ts
apps/portal-server/src/clusterops/slurm/bl/queryJobInfo.ts
apps/portal-server/src/clusterops/slurm/job.ts
apps/portal-server/src/services/desktop.ts
apps/portal-server/src/utils/ssh.ts
apps/portal-server/src/utils/turbovnc.ts
dev/ssh-server/Dockerfile
libs/ssh/src/ssh.ts
libs/ssh/tests/ssh.test.ts
libs/ssh/tests/sshKey.test.ts
libs/ssh/tests/utils.ts

当前，系统所有以用户身份进行的操作（比如查询作业、提交作业等）都需要使用SSH连接以用户身份连接到登录节点后运行命令来操作，且每次执行命令的时候都会开一个新shell，开启新shell的时候会执行shell的配置脚本（比如.bashrc）。如果用户的配置文件中增加了运行时间较长的脚本，那么执行这些命令的时候，系统的反应将会非常慢。
这个PR将以用户身份执行命令的方法改成了**以root身份登录SSH，使用sudo -u 用户 -c 命令 命令行参数**。这样执行命令的时候是开的root用户的shell，而root用户的配置文件一般是比较简单的，这样就绕过了执行用户的配置脚本以用户身份执行命令。
此次PR修改了除了创建交互式作业之外的所有以用户身份执行命令的地方。创建交互式作业部分代码比较复杂，同时涉及到SFTP和SSH，修改后会提高代码复杂度，并且创建交互式作业的过程慢一点可以理解，故没有修改。
受到影响的功能（均在门户系统，管理系统之前只有获取运行中作业调用了slurm指令，但是那是以root身份运行的）
- 查询运行中作业
- 查询交互式作业（仍然需要通过SFTP查询文件，仍然可能有速度慢的问题）
- 获取用户的所有账户
- 提交作业
- 取消作业
- 查询所有作业
- 获取所有桌面
- 连接到桌面
- 关闭桌面

fix(mis): 以root身份登录SSH，使用su命令以用户身份运行命令

---

apps/mis-web/src/components/PlatformRoleSelector.tsx
apps/mis-web/src/components/TenantRoleSelector.tsx
apps/mis-web/src/pageComponents/admin/AllUsersTable.tsx
apps/mis-web/src/pageComponents/init/InitUsersAndAccountsTable.tsx
apps/mis-web/src/pageComponents/tenant/AdminUserTable.tsx

管理系统平台管理员管理所有用户和租户管理员管理租户用户功能中，使用下拉框选择用户的角色，和系统初始化时选择用户角色UI相同。
同时：
- 去掉多余的console.log
- 修改两个Selector组件中prop不规范命名：表示多个角色的prop原来为单数role，现在修改为复数roles

fix(mis-web): 管理系统使用下拉框设置用户的平台和租户角色

---

apps/portal-server/src/clusterops/slurm/job.ts

#384 为了提高需要SSH运行命令的功能的加载数据的速度，将很多需要以用户身份运行命令的功能改成以root身份运行命令，其中包括提交作业。但是以root身份提交作业可能会让slurm无法正确获知目前真正的用户，从而错误的设置一些作业的属性（比如stdout输出目录）。这个PR将提交作业重新改成以用户身份登录SSH后提交作业。这可能会降低shell配置文件复杂的用户提交作业的速度，但是提交作业本来就不需要速度快，这个修改可以接受。

fix(portal-server): 以用户身份提交作业

---

apps/mis-server/src/services/admin.ts

根据slurm的文档（https://slurm.schedmd.com/sacctmgr.html#OPT_user ），默认情况下slurm的用户名为小写，创建用户时大写字符会被改成小写，但是SCOW数据库中存储的用户名没有这一变小写的步骤，又因为SQL查询where对比字符串也不考虑大小写（下图），而所以在获取slurm用户后，把slurm的所有用户名拿去数据库中查询数据库中已经存在的用户时，数据库返回的已有的用户的用户名为大小写都有，slurm用户为小写，匹配不上，就报错了。
这个PR在代码中在使用数据库中的用户查询slurm中对应的用户时忽略大小写以绕过这个问题。

fix(mis-server): 修复当用户名有大写字符时，获取已有slurm用户信息时报错

---

apps/portal-server/src/clusterops/slurm/app.ts

#384 把连接VNC类应用时，连接到计算节点的用户名也改成了root，但是SCOW事实上没有要求服务节点也能免密登录到计算节点。这个PR把连接到计算节点的用户名改回了用户名。

fix(portal-server): 连接VNC类应用时，以用户身份SSH连接到计算节点

---

apps/mis-web/src/pageComponents/job/HistoryJobTable.tsx
apps/mis-web/src/pageComponents/job/RunningJobTable.tsx
apps/portal-web/src/pageComponents/job/AllJobsTable.tsx
apps/portal-web/src/pageComponents/job/RunningJobTable.tsx

管理系统和门户系统的作业查询功能优化：
- 查询历史作业的默认时间修改为一周前的一天的第一秒至当天的最后一秒
- 所有查询作业增加刷新按钮

fix(web): 作业查询UI优化

---

apps/portal-server/src/clusterops/slurm/app.ts
libs/ssh/src/ssh.ts
libs/ssh/tests/ssh.test.ts
libs/ssh/tests/utils.ts

#384 后续。查询已有交互式作业和连接到交互式作业都需要浏览文件，之前都需要以用户身份登录SSH和SFTP。这个PR使这两个功能都可以以root身份连接到到SSH和SFTP，以避开加载用户shell配置文件的开销。

fix(portal): 以root身份查询已有交互式作业和连接到交互式作业

---

apps/mis-server/src/services/charging.ts
apps/mis-server/tests/charging/charging.test.ts
apps/mis-web/src/layouts/routes.tsx
apps/mis-web/src/pageComponents/finance/PaymentTable.tsx
apps/mis-web/src/pages/api/finance/payments.ts
protos/server/charging.proto

- 调整租户充值文本
- 修复查看充值记录的bug。在默认不指定账户的情况下后端会返回`accountName`为空的充值记录，在api层处理时遇到问题。

fix(mis): 修复查看充值记录的bug和调整租户充值文本

---

.changeset/config.json
.github/workflows/test-build-publish.yaml
apps/gateway/package.json
package.json
scripts/version.mjs

- 使用changesets管理gateway项目
- 将apps下的所有包的版本关联起来，并增加一个`ci:version`脚本，使得提高任何一个apps下的版本将会同时提高apps下所有包以及根包的版本

chore: 更新changesets工作流

---

.github/workflows/tag-release.yaml
.github/workflows/test-build-publish.yaml
scripts/tag.mjs
scripts/version.mjs

1. 当package.json中的版本变化时，触发tag-release.yml工作流，生成一个新版本的tag并推送到repo
2. 当有新的tag推送到仓库时，触发生成镜像并发布的工作流，构建带有版本号tag的镜像并推送

ci: 新增tag到发布工作流

---

.changeset/curly-beds-drive.md
apps/auth/package.json
apps/auth/src/app.ts
apps/auth/src/config/env.ts
apps/mis-server/package.json
apps/mis-server/src/app.ts
apps/mis-server/src/config/env.ts
apps/portal-server/package.json
apps/portal-server/src/app.ts
apps/portal-server/src/config/env.ts
deploy/local/config-example.py
deploy/local/generate.py
docs/docs/deploy/ops/index.md
pnpm-lock.yaml

`config.py`增加日志输出配置
- `LOG_LEVEL`: 日志等级，可选`trace`, `debug`, `info`, `warn`, `error`
- `LOG_PRETTY`: 是否以易读的方式(pretty)输出日志，如果是false则输出json格式的日志。使用[`pino-pretty`](https://github.com/pinojs/pino-pretty)来pretty print日志

feat: 配置日志输出选项

---

.devcontainer/Dockerfile
.vscode/settings.json
docs/docs/contribution/dev.md
package.json
pnpm-lock.yaml
turbo.json

现在buf已可通过npm安装（https://docs.buf.build/installation#install-the-buf-cli ），所以这个PR将buf增加到了根package.json，有以下好处
- 不再需要手动安装和管理buf
- renovate能和其他npm一样管理buf的版本

chore: 使用npm分发的buf工具

---

.changeset/perfect-countries-itch.md
apps/auth/src/auth/callback.ts
apps/gateway/includes/headers
docs/docs/deploy/config/auth/config.md

当系统没有部署在80端口时，系统在进入认证系统进行登录配置回调地址时，没有包括端口号。因为之前gateway在转发host header的值的时候，使用的是`$host`变量，这个变量不包括端口号。现在把它改成`$http_host`，直接把上游的host header转发到下游，这样下游才能知道端口号的信息。
同时，这个PR还将代码中和文档中涉及到hostname的变量名和文档术语统一到主机名（hostname）。

fix(auth): 修复当部署的端口号非80时，回调地址出错的问题

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.devcontainer.yml
.gitignore
apps/auth/tests/callback.test.ts
apps/auth/tests/ssh.test.ts
apps/auth/tests/utils.ts
dev/ssh-server/Dockerfile
dev/ssh-server/entry.sh
docs/docs/contribution/dev.md
libs/ssh/tests/utils.ts

此PR支持了Dev Container中运行测试开发环境。在启动开发环境时同时测试开发环境，并将开发环境中的容器启动到开发环境所在的容器的网络栈下，以支持在开发环境中使用localhost连接到测试开发服务。
注意：
1. 本PR修改了`ssh-server`的镜像。如果已经在本地构建好了开发环境并启动过测试开发环境，想迁移到dev container，为了保证运行开发环境时`ssh-server`的镜像为最新，请先手动运行`docker compose -f dev/docker-compose.dev.yml build ssh-server`更新`ssh-server`服务的镜像。具体修改有：
- `ssh-server`镜像的root用户密码修改为`root`，test用户密码修改为`test`
- `ssh-server`在启动时支持不存在`/id_rsa.pub`文件的情况，以支持在dev container中启动的情况
2. 如果之前启动过dev container，本次更新后需要重新构建dev container所在容器。
3. dev container需要一些配置才能完整运行测试开发环境。请查看文档https://pkuhpc.github.io/SCOW/docs/contribution/dev部分以配置。

feat(dev): 支持在Dev Container中运行测试开发环境

---

apps/portal-web/src/apis/api.mock.ts

原问题：在测试开发环境下，打开文件管理系统，默认的路径总是为/home/ddadaal。
原因：调用了mock中的getHomeDirectory的api，该api返回为写死的。
修复：将mock中的getHomeDirectory的api的返回改为null，此时调用getHomeDirectory将调用portal-server端的api，返回适应用户身份的默认路径。

fix(portal): 修复在测试开发环境下文件系统的默认路径不为用户目录

---

.changeset/moody-cameras-crash.md
docker/Dockerfile.scow

Next.js有个功能是在构建时保存构建缓存：https://nextjs.org/docs/advanced-features/ci-build-caching。 但是我们用不上这个功能，却白白占据200M+的缓存内容。
这个PR从最终镜像中去除了这些缓存内容，把容器大小从980M减少到了700M左右。

feat: 从镜像中去除next.js的CI Build Cache

---

.changeset/five-donkeys-repair.md
apps/auth/src/auth/ldap/createUser.ts
apps/auth/src/config/auth.ts
docs/docs/deploy/config/auth/ldap.md

在使用LDAP认证系统时，当添加用户时，系统将在新的用户和组节点中预添加进一些属性。
https://pkuhpc.github.io/SCOW/docs/deploy/config/auth/ldap#%E5%88%9B%E5%BB%BA%E7%94%A8%E6%88%B7
但是当用户修改了节点的objectClass时，有的属性可能不允许存在。
这个PR支持通过extraProps，把属性设置为null，来从节点中删除某个特殊的属性值。
这个PR未添加测试，因为对于测试用的LDAP来说，目前预添加的属性均是必要的，不能删除。

feat(auth): LDAP添加用户和组时，支持删除预添加的属性

---

.changeset/young-coats-hunt.md
apps/mis-server/src/bl/importUsers.ts
apps/mis-server/src/services/admin.ts
apps/mis-server/tests/admin/importUsers.test.ts
apps/mis-web/src/pageComponents/admin/ImportUsersTable.tsx
apps/mis-web/src/pages/api/admin/importUsers.ts
protos/server/admin.proto

之前的版本中新增了选择租户导入的功能，现在删除这个功能，只能导入到默认租户default中

feat(mis): 导入用户模块删除租户选择框，只支持导入到默认租户中

---

.changeset/many-humans-work.md
.gitignore
apps/gateway/src/env.ts
apps/portal-web/config.js
apps/portal-web/src/pageComponents/filemanager/UploadModal.tsx
apps/portal-web/src/utils/config.ts
deploy/local/config-example.py
deploy/local/generate.py
deploy/vagrant/scow/scow-deployment/config.py
docs/docs/refs/env/gateway.md

用户部署配置：
修改scow-deployment/config.py文件中的网关配置，取消对GATEWAY 的注释，修改UPLOAD_FILE_SIZE_LIMIT的值，如将默认的1G改为50M：
```py
#
#
GATEWAY = {
"UPLOAD_FILE_SIZE_LIMIT": "50M",
}
```
PR合并前测试步骤，用户部署无需关注：
1、与正常流程一样拉取镜像
2、修改scow-deployment 下的config.py文件，参照用户部署配置，可将UPLOAD_FILE_SIZE_LIMIT的值改为其它值，例如5M。
3、PR未被合并前，还需要修改scow-deployment 下的generate.py，增加了对UPLOAD_FILE_SIZE_LIMIT的配置，具体参考此PR对deploy/local/generate.py文件的修改，复制即可。
4、进入文件管理，点击文件上传，展示了文件上传的最大限制。尝试上传1个10M的文件，失败

feat(portal): 增加文件上传限制可配置功能

---

.changeset/weak-clouds-shop.md
apps/cli/src/cmd/updateCli.ts
docs/docs/deploy/install/scow-cli.md

之前CLI的`update --release`无法使用，因为asset name不正确。这个PR修复了这个问题。

fix(cli): 修复cli更新release版本

---

.changeset/lazy-hotels-buy.md
apps/cli/src/cmd/init.ts
apps/cli/src/compose/cmd.ts
apps/cli/src/compose/index.ts
apps/cli/tests/compose.test.ts
apps/cli/tests/global.d.ts
apps/cli/tests/utils.ts

当配置了fluentd日志时，在生成compose文件或者运行compose命令时，首先创建fluentd的日志目录并修改权限到777。

fix(cli): 当配置了fluentd日志时，在生成compose文件或者运行compose命令时，首先创建fluentd的日志目录

---

.changeset/plenty-carrots-divide.md
apps/mis-web/src/pageComponents/admin/TenantPaymentTable.tsx

当前系统下，平台管理的租户充值记录页面。填入租户名进行条件搜索后，手动将租户输入框清空再点击搜索，结果为空。原因是输入框手动清空后，调用api时会传参tenantName=""，与预期不符。此处fix将其改为传参undefined会得到预期结果

fix(mis-web): 修复平台管理租户充值记录过滤条件tenantName手动清空时结果为空

---

.changeset/blue-singers-tan.md
docs/docs/deploy/install/scow-cli.md

增加scow-cli下载及修改权限的参考命令，让用户使用起来更简单
```bash
```bash
yum install wget
wget https://github.com/PKUHPC/SCOW/releases/download/latest/cli-x64
mv cli-x64 cli
#修改文件权限
chmod 777 cli
```

docs:  丰富 scow-cli 文档，增加下载参考命令

---

.changeset/calm-sheep-clap.md
libs/ssh/src/key.ts
libs/ssh/src/sftp.ts
libs/ssh/src/ssh.ts
libs/ssh/tests/sshKey.test.ts
libs/ssh/tests/utils.ts

目前，SCOW在登录一个用户时，如果发现无法直接公钥登录登录节点，则SCOW会自动给这个用户配置免密登录，步骤为：
1. 用用户的用户名和密码登录登录节点
2. 如果用户的家目录存在，则把SCOW公钥写入~/.ssh/authorized_keys，如果文件不存在则创建
3. 如果家目录不存在，则
4. 以root身份登录登录节点
5. 创建用户的家目录
6. 创建~/.ssh/authorized_keys文件并写入内容
7. 修改目录和文件的权限和owner  
但是有时候SCOW无法直接公钥登录用户的原因不是因为authorized_keys不存在，而是因为文件存在但是文件中不存在SCOW的公钥。目前的方案的第二步中，如果authorized_keys已经存在，则SCOW将会直接覆盖authorized_keys文件。
SCOW在插入公钥的时候需要先判断authorized_keys文件是否存在，如果已经存在，则直接把SCOW的公钥内容写入authorized_keys文件后面。

fix(ssh): 配置SCOW免密认证时，如果用户的authorized_keys已存在，则将SCOW的公钥插入，而不覆盖已有的authorized_keys文件

---

.changeset/pretty-goats-type.md
apps/cli/package.json
apps/cli/src/cmd/updateCli.ts
apps/cli/src/config/proxy.ts
docs/docs/deploy/install/scow-cli.md
pnpm-lock.yaml

现在在使用CLI更新CLI时支持设置HTTP代理，通过`HTTPS_PROXY`, `https_proxy`, `HTTP_PROXY`, `http_proxy`环境变量设置。

feat(cli): CLI支持设置HTTP代理

---

.github/workflows/test-build-publish.yaml
scripts/tag.mjs

当@scow/grpc-api版本变化时，创建一个api-v{版本}的tag并push到仓库中。这使得用户可以直接使用git的tag来找到想要使用SCOW API版本的相关文件。

ci: 当@scow/grpc-api版本变化时，创建一个api-v{版本}的tag

---

.changeset/short-spiders-obey.md
apps/portal-web/src/pages/shell/[cluster]/[[...path]].tsx

当前系统Shell页面展示的是集群ID，用户造成识别困难。此次改动展示集群name

feat(portal-web): Shell 页面标题展示集群name

---

.changeset/tiny-rocks-marry.md
apps/cli/package.json
apps/cli/src/cmd/checkConfig.ts
apps/cli/src/index.ts
docs/docs/deploy/install/scow-cli.md
pnpm-lock.yaml

CLI增加`check-config`子命令，可以检查SCOW配置文件格式。
会检查的配置文件：
- 交互式应用配置（apps/*.yaml）
- 集群配置文件（clusters/*.yaml）
- 集群说明配置（clusterTexts.yaml）
- 公共配置文件（common.yaml）
- UI配置（ui.yaml）
- 管理系统配置（mis.yaml）：只有当install.yaml指定了部署管理系统时会检查
- 门户系统配置（portal.yaml）：只有当install.yaml指定了部署门户系统时会检查

feat(cli): check-config子命令，在不启动SCOW的情况下检查SCOW配置文件格式

---

libs/protos/buf.gen.yaml
libs/protos/package.json
pnpm-lock.yaml

之前都是使用的ts-proto在buf的plugin云上托管的插件来生成proto文件（ https://github.com/stephenh/ts-proto#buf ），但是buf自己没有给生成插件加缓存，每次生成proto文件都需要去云上获取插件，一旦网络出现一点波动就出问题。
这个PR在@scow/protos项目的本地安装了ts-proto，并使用本地的ts-proto进行pb文件的生成。

refactor: 使用本地的ts-proto生成pb文件

---

.changeset/rich-ducks-visit.md
apps/mis-web/src/auth/token.ts
apps/mis-web/src/models/User.ts
apps/mis-web/src/pages/api/auth/validateToken.ts
apps/mis-web/src/stores/UserStore.ts
apps/portal-web/src/auth/token.ts
apps/portal-web/src/models/User.ts
apps/portal-web/src/pages/api/auth/validateToken.ts
apps/portal-web/src/stores/UserStore.ts
libs/web/src/layouts/base/header/UserIndicator.tsx
libs/web/src/layouts/base/types.ts

#591 支持了从认证系统中获取用户姓名。这个PR使在门户和管理系统登录后，显示在网页右上角的用户姓名为从认证系统中获取的用户姓名。如果从认证系统中获取不到用户名，则使用用户的ID显示。
在一个LDAP的集群中的测试方法：
1. 登录门户系统，查看登录后右上角显示的用户姓名是否为LDAP里用户的姓名
2. 修改管理系统数据库，在`user`表中将一个用户的姓名列修改为其他的，然后登录管理系统，查看登录后右上角显示的用户姓名是否为LDAP里用户的姓名

fix(web): 前端显示用户姓名时使用认证系统返回的用户姓名

---

.changeset/fifty-adults-jam.md
apps/mis-web/package.json
apps/mis-web/src/pages/_app.tsx
apps/mis-web/src/pages/_document.tsx
apps/portal-web/package.json
apps/portal-web/src/pages/_app.tsx
apps/portal-web/src/pages/_document.tsx
libs/web/package.json
libs/web/src/layouts/darkMode.tsx
pnpm-lock.yaml

之前，每次第一次加载页面（例如刷新浏览器）时，页面布局和黑暗模式会混乱：
修复后：
布局闪动（称为layout shift）是因为HTML是在浏览器端刷新好了发到了客户端，但是样式不是在服务器端渲染的而是在客户端渲染的。当HTML发到客户端、浏览器开始渲染HTML时并没有样式，故一开始就会出现只有HTML没有样式的问题。这个问题的解决参考了：https://github.com/ant-design/ant-design/issues/40610，在Custom Document中增加了在服务器端提取样式的代码。
黑暗模式是另一个问题。之前，用户的黑暗模式的选择是存放在local storage里的，服务器无法访问，故服务器在渲染时只能用默认的黑色或者白色渲染，然后把渲染好的样式发送到客户端，然后客户端再读取用户的选择，再调整样式，这对选择使用另一种模式的用户都会出现先出现了黑色（白色）的样式（服务器端渲染的），然后在客户端换成了另一个（客户端渲染的）。这个PR的解决方案是把用户的黑暗模式的选择存放到cookie（scow-dark）中，这样服务器端就可以知道用户的选项，从而在服务器端渲染时就使用客户端的选择渲染样式。

fix(web): 修复web项目浏览器刷新时页面布局闪动的问题

---

.changeset/modern-scissors-kneel.md
docs/docs/deploy/config/cluster-config.md
docs/docs/deploy/config/portal/apps/apps/jupyter.md
docs/docs/deploy/config/portal/apps/apps/vscode.md
docs/docs/deploy/config/portal/apps/configure-vnc-app.md
docs/docs/deploy/config/portal/apps/configure-web-app.md
libs/config/src/app.ts
libs/config/src/cluster.ts
libs/libconfig/src/fileConfig.ts
libs/libconfig/tests/fileConfig.test.ts

现在集群配置文件只能读clusters/{clusterId}.yaml，但是应该允许读clusters/{clusterId}/config.yaml。同样，应用程序除了apps/{appId}.yaml，还应该允许读apps/{appId}/config.yaml。如果两个文件同时存在，优先读后者。
这是为了同时为了兼容之前的配置以及未来的扩展性，例如
- 支持只有某个集群能用的应用配置
- 给交互式应用增加图标文件

feat: 集群和应用配置文件可放在子文件夹中

---

.changeset/lemon-spoons-allow.md
apps/auth/src/auth/cacheInfo.ts
apps/auth/src/config/auth.ts
apps/auth/src/config/env.ts
apps/cli/assets/config/auth.yml
docs/docs/deploy/config/auth/config.md
docs/docs/refs/env/auth.md

认证系统配置增加模仿用户功能（mockUsers）功能。当登录用户的ID为某个模仿用户时，将登录用户改为另一个用户。
修改此配置无需重启认证系统。
这允许管理员作为任何用户身份登录SCOW。
```yaml
mockUsers:
fromUser1: toUser1
```
此PR同时将认证系统的模板写到了cli的初始认证系统配置文件中。

feat(auth): 模仿用户功能

---

.changeset/fast-flowers-begin.md
apps/auth/src/routes/validateToken.ts
docs/docs/integration/auth/impl.md
libs/auth/src/validateToken.ts
libs/auth/tests/validateToken.test.ts

将认证系统的[GET /validateToken]增加public前缀，使任何人可以访问此API。主要用于方便第三方开发。
这个API是根据token访问用户信息，如果一个用户已经有了token，那么它本来就应该可以访问用户信息。事实上目前mis/portal-web均已有API Route包装了认证系统的GET /validateToken，本来就已经大家都可以访问了。
已有的认证系统实现应尽快修改GET /validateToken为GET /public/validateToken。

feat(auth): 认证系统/validateToken API修改为/public/validateToken

---

.changeset/angry-chicken-tan.md
scripts/version.mjs

新格式为：
```markdown
发布于：2023/5/9 11:53:59
配置文件版本：0.2.1
- 测试 ([e42cd135](https://github.com/PKUHPC/SCOW/commit/e42cd13536a922d49fa018114e51f0e28f33512a))
SCOW API版本：0.3.1
- 测试 ([e42cd135](https://github.com/PKUHPC/SCOW/commit/e42cd13536a922d49fa018114e51f0e28f33512a))
- 测试 ([e42cd135](https://github.com/PKUHPC/SCOW/commit/e42cd13536a922d49fa018114e51f0e28f33512a))
```

chore: 更新更新日志的格式

---

.changeset/pink-news-chew.md
apps/portal-web/src/pageComponents/app/AppSessionsTable.tsx

fix(portal-web): 修改已创建的交互式应用页面checkbox居中显示

---

.changeset/friendly-games-complain.md
apps/mis-web/package.json
apps/portal-web/package.json
libs/web/package.json
package.json
pnpm-lock.yaml
renovate.json

固定Next.js版本到13.2.4。从13.3开始，next.js无法再绑定server的upgrade事件，即无法再在next.js中使用WebSocket。正在寻找替代方案。

fix(portal-web): 临时解决Shell、桌面和VNC类应用不可用的问题

---

.changeset/mean-pillows-hide.md
apps/portal-server/src/clusterops/api/app.ts
apps/portal-server/src/clusterops/slurm/app.ts
apps/portal-server/src/services/app.ts
apps/portal-server/tests/app/getAppLastSubmission.test.ts
apps/portal-server/tests/file/utils.ts
apps/portal-web/src/apis/api.mock.ts
apps/portal-web/src/apis/api.ts
apps/portal-web/src/pageComponents/app/LaunchAppForm.tsx
apps/portal-web/src/pageComponents/job/AccountSelector.tsx
apps/portal-web/src/pages/api/app/getAppLastSubmission.ts
dev/vagrant/config/apps/vscode.yaml
libs/config/src/portal.ts
protos/portal/app.proto

1.增加了用于保存交互式应用上一次提交记录的家目录路径
`../scow/apps/[appId]/last_submission.json`
2.增加了提取上一次提交记录的GET的API接口
3.修改了本地vagrant集群vscode.yaml文件配置，增加了自定义的配置HTML表单
因为目前本地vagrant没有部署相应应用，如果后期会实装应用的话，版本号可能会有影响，如果有需要将改回
```
attributes:
- type: select
name: selectVersion
label: 选择版本
required: true  # 用户必须选择一个版本
placeholder: 选择code-server的版本  # 提示信息
select:
- value: code-server/4.8.0
label: version 4.8.0
- value: code-server/4.9.0
label: version 4.9.0
- type: text
name: sbatchOptions
label: 其他sbatch参数
required: false
placeholder: "比如：--gpus gres:2 --time 10"
```
1. 打开创建交互式应用页面，表单填入默认集群
1. 按默认集群查找该集群下是否有上一次提交记录，如果没有则填入系统默认值，如果有进行以下判断填入表单
1. 判断上一次提交信息中的分区是否仍在当前集群配置下
> -    如果是
> 
> >    将上一次的分区值填入表单
> >    继续判断qos, cpu核心数是否仍满足当前集群配置
> >    如果满足，填入上一次的填入值
> >    如果不满足，填入当前配置下的默认值
> 
> -    如果否
> 
> > …

feat(portal): 交互式应用部分需要记录用户之前填或者选的内容

---

.changeset/eight-crews-hang.md
apps/mis-web/src/auth/cookie.ts
apps/portal-web/src/auth/cookie.ts

关闭浏览器后，登录cookie即失效。token的失效规则没有变化（`tokenTimeoutSeconds`配置）。

fix(web): 登录信息关闭浏览器后即失效

---

dev/ssh-server/Dockerfile

更新测试开发环境的alpine到3.18，并对应更新openssh到9.3_p1-r3

fix(devenv): 更新测试开发环境的alpine和openssh版本

---

.changeset/quiet-feet-poke.md
apps/portal-web/src/pageComponents/filemanager/FileTable.tsx
apps/portal-web/src/utils/format.ts

提交作业页面的总内存容量展示与文件管理的文件大小展示的公用函数formatSize，在使用时提交作业页面传的size单位为MB, unitMap以MB开始。而文件管理使用时size的单位是B, unitMap以KB开始，所以造成其中一个展示单位出现问题。
此次修改将传参的size和unitMap的起始单位保持一致，加上注释便于使用时更好的理解

fix(portal-web): 修复 formatSize 公共函数传参单位统一问题

---

.changeset/dirty-spoons-visit.md
apps/mis-web/src/pages/_document.tsx
apps/portal-web/src/pages/_document.tsx

原本 apps/portal-web/src/pages/_document.tsx 及 apps/portal-web/src/pages/_document.tsx文件中的组件里多写了一个逗号，现去掉

fix(web): 去掉 web 端多余的逗号

---

.changeset/tall-hats-exercise.md
apps/mis-server/src/services/tenant.ts
apps/mis-server/tests/tenant/tenant.test.ts

租户信息展示的是数据库user自增id， 此处pr改为user_id

fix(mis): 租户信息管理员 id 展示 userId 修复

---

.changeset/red-candles-sleep.md
apps/portal-web/src/pageComponents/app/AppSessionsTable.tsx

交互式应用列表状态单选进行中和排队中改为勾选是否只展示未结束的作业，默认不勾选，展示所有作业

feat(portal-web): 交互式应用列表状态筛选改为勾选只展示未结束的作业

---

.changeset/loud-books-tie.md
apps/mis-web/config.js
apps/mis-web/src/layouts/BaseLayout.tsx
apps/mis-web/src/pages/_app.tsx
apps/mis-web/src/utils/config.ts
apps/portal-web/config.js
apps/portal-web/src/layouts/BaseLayout.tsx
apps/portal-web/src/pages/_app.tsx
apps/portal-web/src/utils/config.ts
libs/web/src/layouts/base/BaseLayout.tsx
libs/web/src/layouts/base/Footer.tsx

改动：
管理系统和门户系统增加统一Footer，展示github地址链接和版本信息，此Footer放在用户自定义Footer之上，用分割线分开
没有自定义footer：
有自定义footer：

feat(mis-web, portal-web):  门户和管理系统添加 footer 展示 SCOW 版本和 github 跳转链接

---

.changeset/few-students-hug.md
apps/portal-web/package.json

NEXT_PUBLIC_USE_MOCK = 1时，portal-web的集群配置路径会选择本项目下的config文件而不是/dev/vagrant/clusters。 会导致cluster配置和本地vagrant不一致，将其修复为NEXT_PUBLIC_USE_MOCK = 0；

fix(potal-web): 修复 dev container 和本地 vagrant 开发模式下集群配置不一致问题

---

.changeset/lazy-brooms-dream.md
apps/mis-server/src/services/user.ts
apps/mis-server/tests/admin/user.test.ts
protos/hook/hook.proto
protos/server/user.proto

mis-server增加一个API：addUser，用于创建用户时仅在scow的数据库中新增用户的场景，如实现自定义认证系统时不需要往LDAP增加用户，外部系统可以调用此API往scow数据库中增加新用户。与createUser的区别在于不需要password，不调用auth服务，暂不将公钥插入用户authorized_keys

feat(mis): 增加仅在 scow 数据库新增用户的 API

---

.changeset/many-boxes-bow.md
apps/mis-web/src/utils/config.ts
apps/portal-web/src/utils/config.ts

因为 #681 [feat(auth): 认证系统增加管理用户账户关系相关 API](https://github.com/PKUHPC/SCOW/pull/681/files#top) 时修改为capabilities的每个属性可以为undefined出现了config中类型匹配错误，导致本地5001端口无法启动
本PR将下述相关接口的类型按照 #681 的功能需求修改为`boolean | undefined`
ENABLE_CHANGE_PASSWORD
CREATE_USER_CONFIG中的authSupportsCreateUser
修改后本地启动无异常

fix(portal,mis): config中ENABLE_CHANGE_PASSWORD相关的类型错误

---

libs/rich-error-model/buf.gen.yaml
libs/rich-error-model/jest.config.js
libs/rich-error-model/package.json
libs/rich-error-model/src/create.ts
libs/rich-error-model/src/errorDetail.ts
libs/rich-error-model/src/index.ts
libs/rich-error-model/src/parse.ts
libs/rich-error-model/tests/global.d.ts
libs/rich-error-model/tests/server.test.ts
libs/rich-error-model/tsconfig.build.json
libs/rich-error-model/tsconfig.json
pnpm-lock.yaml
turbo.json

增加`@scow/rich-error-model`包以帮助处理gRPC Rich Error Model。
用法参考libs/rich-error-model/tests/server.test.ts。
```ts
import { ErrorInfo, LocalizedMessage } from "@scow/rich-error-model";
ErrorInfo.create({ domain: "test.com", reason: "123", metadata: { test1: "test" } });
LocalizedMessage.create({ locale: "zh-CN", message: "123" });
```
```ts
import { DetailedError } from "@scow/rich-error-model";
throw new DetailedError({
code: status.ALREADY_EXISTS,
message: errorMessage,
details: [errorInfo(), localizedMessage()],
});
```
```ts
import { parseErrorDetails } from "@scow/rich-error-model";
try {
await asyncUnaryCall(createClient(), "onEvent", {
metadata: { time: new Date().toISOString() },
event: { $case: "userAdded", userAdded: { tenantName: "123", userId: "123" } },
});
} catch (e) {
const ex = …
```

chore: 增加处理gRPC Rich Error Model的模块

---

.changeset/shaggy-garlics-pump.md
libs/rich-error-model/package.json

fix(libs): 修复rich-error-model包不能导入的问题

---

.changeset/nine-mangos-behave.md
libs/rich-error-model/package.json

copyDist脚本在构建镜像时不能正常运行，原因是rich-error-model包的package.json中缺少files字段
这个pr补充了这个字段

fix(libs): 修复构建镜像时rich-error-model包存在的问题

---

.changeset/pink-flies-pay.md
apps/portal-web/src/pageComponents/app/LaunchAppForm.tsx
apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx

在提交作业和交互式应用时，单节点核心数可选择的上限为整个分区的核心总数，这个pr修复这个bug，现在可选择的核心数上限为核心总数除以节点总数

fix(portal-web): 单节点CPU数和单节点GPU数显示为总数

---

.changeset/gold-cows-smell.md
apps/cli/assets/install.yaml
apps/cli/src/cmd/migrate.ts
apps/cli/src/compose/index.ts
apps/cli/src/config/install.ts

现有情况下，用户通过ghcr.io拉取scow镜像，不便于scow部署信息的收集。拉取地址改为mirrors.eecser.com/pkuhpc-icode/scow可以实现该需求，故需要确保用户每次都从mirrors.pku.edu.cn/pkuhpc-icode-scow(将会代理到mirrors.eecser.com/pkuhpc-icode/scow)拉取镜像。
cli隐藏用户配置image镜像地址，默认镜像地址改为：mirrors.pku.edu.cn/pkuhpc-icode/scow，且生成的`install.yaml`文件中隐藏image属性（开发测试可以配置）。
cli文件已在本地集群中验证可用。

feat(cli): cli中隐藏用户可配置镜像地址，默认为：mirrors.pku.edu.cn/pkuhpc-icode/scow

---

.github/workflows/test-build-publish.yaml

改动：
1. 在现有的workflow下，在Test, Build and Publish Projects内的build images job里新增使用账号密码docker login 到PKU_CR：`mirrors.eecser.com`，此账号密码保存在github secrets内，key分别为`PKUREGISTRY_USERNAME`和`PKUREGISTRY_PASSWORD`。
2. 将build好的image上传至`mirrors.eecser.com/pkuhpc-icode/xxx: {tag}`下
3. 通过`mirror.pku.edu.cn/pkuhpc-icode/xxx: {tag}`可以拉到最新push到`mirrors.eecser.com/pkuhpc-icode/xxx: {tag}`的镜像
自测：
已在58集群拉取到该image
关于push的速度问题： 经测试偶尔时间达到将近十多分钟，可以考虑后续只对release或者合master的image 推到该仓库，其他pr的image继续使用github的仓库即可。

ci: github worflow新增push PKU repository

---

.changeset/early-moles-rescue.md
apps/portal-server/assets/slurm/server_entry.sh
apps/portal-server/src/clusterops/slurm/app.ts
apps/portal-web/assets/slurm/server_entry.sh

此PR通过在`script.sh`和`xstartup`脚本加上`#!/bin/bash -l`，`script.sh`增加可执行权限，更改`scirpt.sh`执行方式为`bash -l `
解决了source执行无法获取profile中变量的问题
- 修改前
手动更改计算机节点profile中环境变量
web/vnc应用都无法获取到变更后的环境变量
- 修改后
> web应用
> `script.sh`脚本增加权限
> ![image](https://github.com/PKUHPC/SCOW/assets/43978285/d14a8182-e927-43ba-b117-4419f6efaadd)
> script.sh脚本首行自动加入`#!/bin/bash -l  `
> ![image](https://github.com/PKUHPC/SCOW/assets/43978285/290780de-7822-4efe-8a2c-9fd6e2ea9172)
> 可以正常获取到计算机节点上Profile中变更的环境变量
> ![image](https://github.com/PKUHPC/SCOW/assets/43978285/43d7fcf9-832f-4481-8108-de0aac48fe24)
> vnc应用
> `xstartup`脚本首行自动加入#`!/bin/bash -l  `
> ![image](https://github.com/PKUHPC/SCOW/assets/43978285/db281688-bf27-4a89-85b3-4f7f589c5980)
> 可以正常获取到计算机节点上Profile中变更的环境变量
> …

fix(portal-server): 交互式任务脚本里执行script.sh不能使用source的方式

---

.changeset/good-boats-collect.md
apps/portal-server/src/clusterops/app.ts
apps/portal-server/src/services/app.ts
apps/portal-web/package.json
apps/portal-web/src/pageComponents/app/LaunchAppForm.tsx
apps/portal-web/src/pages/api/app/createAppSession.ts
pnpm-lock.yaml

**现状**
创建交互式应用失败时不能显示详细信息
**做了什么**
此PR使用`rich-error-model`重构了创建交互式应用时的错误信息处理
在创建交互式应用失败时创建`modal`提示错误详细信息
`slurm返回错误`👇
`交互式应用配置找不到时返回错误`👇
`配置表单中选择项出问题时返回错误`👇

fix(portal): 提交交互式应用任务失败提示信息不完全

---

.changeset/mighty-spies-grab.md
apps/mis-web/package.json
apps/mis-web/src/layouts/AntdConfigProvider.tsx
apps/mis-web/src/pages/_app.tsx
apps/portal-web/package.json
apps/portal-web/src/layouts/AntdConfigProvider.tsx
apps/portal-web/src/pages/_app.tsx
libs/web/package.json
pnpm-lock.yaml

按现在的前端的架构，页面主要由实现在libs/web下的总体布局以及实现在portal-web或者mis-web里的业务组件组成。portal-web和mis-web将会从libs/web导入UI组件并渲染在页面上。特别的，portal-web和mis-web将会在libs/web下导入一个AntdConfigProvider组件，这个组件引入了`antd`的ConfigProvider，用于配置UI的主题。
在上一次依赖项升级后，libs/web中的AntdConfigProvider组件配置的主题不会影响portal-web和mis-web中的UI。
此问题具体原因不明，但有可能是因为pnpm的依赖解析算法导致导入了多个antd或者react实例。已确认并非libs/web项目的peerDependencies导致的。本PR同时修改了libs/web项目的peerDependencies，在其中加入了react, react-dom等其他依赖项，但并未解决此问题。
此PR提出了临时的解决方案，即在portal-web和mis-web中复制粘贴一份AntdConfigProvider组件。这个组件直接从antd导入`ConfigProvider`来配置portal-web和mis-web中的UI的主题，并同时使用了libs/web中的`AntdConfigProvider`以配置libs/web下的UI。

fix(web): 修复antd主题未能应用到整体页面

---

dev/ssh-server/Dockerfile

测试开发环境的ssh-server的镜像使用alpine:3.18作为base path并指定了openssh版本，但是指定的版本在alpine:3.18的repo不存在了。这个PR使得这个镜像不指定具体的openssh版本。

fix(dev): 修复ssh-server容器构建

---

.github/workflows/test-build-publish.yaml

回滚#708。由于github actions访问北大镜像库速度较慢，故此PR使CI时不push镜像到北大镜像库中。北大镜像库
中通过webhook和镜像的方式从ghcr中同步镜像。

ci: 去除push镜像到北大镜像库

---

.changeset/forty-books-tease.md
apps/mis-server/src/tasks/fetch.ts

当前版本中, 当导入一批作业时, 会先逐个计算每条作业的价格, 并尝试将作业写入数据库, 收集所有可导入数据库的已计费作业. 再统一进行扣费操作.
现在将流程改为: 对于一条作业, 先计费, 再导入作业, 再扣费; 完整进行上述流程后再继续导入下一条作业

feat(mis-server): 调整导入作业流程

---

.changeset/fair-masks-smile.md
docs/docs/deploy/config/customization/webui.md

文档有疏漏，路径少了一个s，代码中写的路径是icons，用户根据原文档无法修改icon，本PR修正此问题。
定义文件路径的代码 apps/mis-web/src/pages/api/icon.ts ：
```ts
import { DEFAULT_CONFIG_BASE_PATH } from "@scow/config/build/constants";
import { serveIcon } from "@scow/lib-web/build/routes/icon/icon";
import { NextApiRequest, NextApiResponse } from "next";
const BUILTIN_DEFAULT_DIR = "assets/icons";
export default (req: NextApiRequest, res: NextApiResponse) =>
serveIcon(req, res, BUILTIN_DEFAULT_DIR, DEFAULT_CONFIG_BASE_PATH);
```

fix(doc): 修正自定义 favicon 文档中的错误信息

---

.changeset/afraid-tigers-count.md
.changeset/itchy-emus-divide.md
apps/mis-server/src/services/account.ts
apps/mis-server/tests/admin/whitelist.test.ts
apps/mis-web/src/apis/api.mock.ts
apps/mis-web/src/models/UserSchemaModel.ts
apps/mis-web/src/pageComponents/tenant/AccountTable.tsx
apps/mis-web/src/pageComponents/tenant/AccountWhitelistTable.tsx
libs/web/src/components/FilterFormContainer.tsx
protos/server/account.proto

**在租户管理的账户列表下做了以下修改**
1. 在右上角添加所有账户、欠费账户、封锁账户，括号内为数量，点击后显示相应的账户，点击后动作与用户列表优化相同
2. 去除原有搜索左边的筛选条件
3. 拥有者后增加用户数量显示列
4. 增加按余额和状态排序
**在租户管理的白名单账户列表下做了以下修改**
1. 增加按账户名搜索功能
2. 搜索栏下增加白名单数量和白名单欠费合计金额显示，金额显示为与其他页面统一产品需求调整为显示小数点后3位小数
3. 拥有者后增加账户余额显示列
4. 增加按账户名和余额排序

feat(mis): 租户管理下账户列表及白名单账户列表显示优化 

---

.github/workflows/test-build-publish.yaml

Buf CLI目前从npm中获取，CI中不再需要单独安装buf。

ci: 从CI中去除安装buf步骤

---

.changeset/spotty-gorillas-worry.md
apps/portal-server/config/portal.yaml
apps/portal-web/config.js
apps/portal-web/config/portal.yaml
apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
apps/portal-web/src/pages/jobs/submit.tsx
apps/portal-web/src/utils/config.ts
dev/vagrant/config/portal.yaml
docs/docs/deploy/config/portal/intro.md
libs/config/src/portal.ts

```shell 
submitPromptText:
defaultText: "#此处参数设置的优先级高于页面其它地方，两者冲突时以此处为准"
hostnameMap:
a.com: "a.com's 提交作业命令框中的提示语"
```

feat: 增加提交作业的命令框中的提示语句可配置

---

.changeset/thin-peaches-fly.md
apps/mis-web/src/pages/api/profile/changePassword.ts
apps/mis-web/src/pages/api/tenant/create.ts
apps/mis-web/src/pages/api/users/create.ts

mis-web处的创建用户，修改密码以及创建租户处的schema
```typescript
Type.Union([Type.String(), Type.Undefined()])
```
修改为
```typescript
Type.Optional(Type.String())
```

fix(mis-web): 修复 Schema 中使用 Type.Union([Type.String(), Type.Undefined()])错误，改为 Type.Optional(Type.String())

---

.changeset/ninety-planets-pretend.md
apps/mis-web/src/auth/requireAuth.tsx
apps/mis-web/src/pages/accounts/[accountName]/info.tsx
apps/mis-web/src/pages/admin/info.tsx
apps/mis-web/src/pages/tenant/info.tsx
apps/portal-web/src/auth/requireAuth.tsx
apps/portal-web/src/pages/desktop/index.tsx

fix(web): 退出登录或登陆过期时跳转页面修改

---

.changeset/tiny-chicken-cheat.md
apps/portal-web/src/stores/DefaultClusterStore.ts

问题复现：先通过操作作业或者交互式应用，scow将在浏览器中存储默认集群的id，修改集群配置文件名字，重启服务后，发现重新登录scow会无法正确渲染，需清除浏览器缓存后才能渲染。系统取集群的id通过join拼接路径，join的Path不能为空。
解决：给默认集群加一个默认值，设为第一个集群

fix(portal-web): 修复 localStorage 设置了默认集群但默认集群在 scow 上不存在导致网站无法加载的问题

---

.changeset/ten-islands-tickle.md
apps/mis-server/src/services/job.ts

修改作业时限时，如果用户不是平台管理员，会查询单个作业信息，此时由于mis-server对jobIdList的遍历存在问题，会导致获取不到job信息报错
1. 将```for in``` 改为```for of``` 遍历jobIdList
2. 每次遍历时捕获错误，使得正确的job信息可以得到返回。

fix(mis-server): 修复调用适配器 getJobById 时，循环 jobIdList 获取 jobId 问题

---

.changeset/honest-mails-brake.md
apps/auth/src/auth/loginHtml.ts
apps/auth/src/config/env.ts
apps/cli/src/compose/index.ts

之前 auth 登录界面的 logo 加载的路径是 BASE_PATH + LOGO_URL，但实际上 logo 的请求是发送到了 portal web 中。所以正确的路径应该是 PORTAL_BASE_PATH + LOGO_URL
为 auth 添加环境变量 PORTAL_BASE_PATH，然后在加载 logo 的 url 修改为 PORTAL_BASE_PATH + LOGO_URL
由于增加了 auth 的环境变量，所以需要更新 cli 更新方式：https://pkuhpc.github.io/SCOW/docs/deploy/install/scow-cli

fix(auth): 修复 auth logo 路径不正确的问题

---

.changeset/pretty-dancers-hunt.md
.changeset/rich-hotels-boil.md
apps/mis-server/src/services/job.ts
apps/mis-web/src/pageComponents/job/ChangeJobTimeLimitModal.tsx
apps/mis-web/src/pages/api/job/changeJobTimeLimit.ts
apps/mis-web/src/server/jobAccessible.ts
apps/portal-web/src/models/job.ts
libs/web/src/utils/datetime.ts
protos/server/job.proto

当前修改作业时限的传参为delta，用户选择是增加或者减少时限
且当前未对作业的运行时间和设置的时限做校验，当修改后的时限小于当前作业运行时间时，适配器侧会直接抛出错误将作业终止
用户直接输入修改的作业时限
同时mis-web的后端会对当前运行时间和用户设置的作业时限进行比较，当设置的时限未大于当前运行时间时，将会抛出错误，而不是请求适配器侧将作业终止。
请求错误处理如下

feat(mis): 修改作业时限优化，将增加减少时限改为直接设置作业时限，并且检查是否大于作业的运行时间

---

.changeset/seven-gorillas-play.md
apps/mis-server/src/services/account.ts
apps/mis-web/src/pages/tenant/accounts/create.tsx

1. 限制创建账户的拥有者为当前租户下的用户，并优化提示信息为 租户 xxx 下用户 xxx 不存在

fix(mis): 限制创建账户时的拥有者仅为当前租户下的用户

---

.changeset/six-worms-repair.md
apps/mis-server/src/services/account.ts
apps/mis-server/tests/admin/whitelist.test.ts
apps/mis-web/src/pageComponents/accounts/AccountTable.tsx
apps/mis-web/src/pageComponents/admin/AllTenantsTable.tsx
apps/mis-web/src/pageComponents/job/HistoryJobTable.tsx
apps/mis-web/src/pageComponents/job/RunningJobTable.tsx
apps/mis-web/src/pageComponents/tenant/AccountWhitelistTable.tsx
apps/portal-web/src/pageComponents/job/AllJobsTable.tsx
apps/portal-web/src/pageComponents/job/RunningJobTable.tsx

fix(web): 用户、账户、作业显示方式和名称统一

---

.changeset/big-hats-return.md
apps/mis-server/src/plugins/clusters.ts
apps/mis-server/src/services/user.ts
apps/mis-web/src/pageComponents/users/AddUserButton.tsx
apps/mis-web/src/pages/_app.tsx
apps/mis-web/src/pages/api/users/addToAccount.ts

原本涉及adapter的部分接口，未能展示从slurm返回的错误，如创建账户时，用户名中有大写，截图：
现在修改返回信息，将其暴露：
账户的用户管理，添加的用户名中有大写，报错如下：
修改后：

fix(mis): 暴露操作集群时后端返回的错误信息

---

.changeset/honest-spies-think.md
apps/mis-server/src/services/user.ts
apps/mis-web/src/pageComponents/users/AddUserButton.tsx
apps/mis-web/src/pages/api/users/addToAccount.ts

fix(mis-web): 修复账户添加用户提示语

---

.changeset/cold-items-whisper.md
apps/portal-server/src/utils/desktops.ts
apps/portal-server/tests/utils/desktop.test.ts

使用时，如果一个新用户在没有提交作业或者交互式应用时，进入到桌面页面，会在工作目录下以root身份创建桌面信息保存目录。而这会导致用户之后使用其他相关工作目录功能报错。
创建userDesktopDir时 以用户身份操作而不是使用root身份创建

fix(portal-server): 修复桌面功能以 root 创建文件夹导致工作目录权限错误问题

---

.changeset/thirty-avocados-admire.md
.changeset/warm-radios-itch.md
apps/mis-server/src/services/user.ts
apps/mis-web/src/apis/api.mock.ts
apps/mis-web/src/components/OperationLogTable.tsx
apps/mis-web/src/models/operationLog.ts
apps/mis-web/src/pages/api/log/getOperationLog.ts
protos/server/user.proto

1. 操作日志搜索精确到秒
2. 新增了一个接口负责将操作日志的userId查询对应的userName展示
3. 操作日志table每页默认展示50条记录

feat(mis): 操作日志搜索时间精度到秒，展示操作者姓名以及每页默认展示 50 条记录

---

.changeset/warm-ducks-pretend.md
apps/portal-web/src/pageComponents/filemanager/FileManager.tsx

目前使用的next版本13.4.10，如果增加了legacyBehavior，会影响target="_blank"的核心效果（即在新窗口或标签中打开链接），此pr去掉FileManager中的该属性，保证能在打开终端时新开页面

fix(portal-web): 去掉 legacyBehavior，会影响 target=“_blank” 在新窗口或标签中打开链接的效果

---

.changeset/dirty-cobras-happen.md
apps/auth/src/auth/callback.ts
apps/mis-web/src/pages/api/auth/callback.ts
apps/portal-web/src/pages/api/auth/callback.ts

用户登录操作日志记录在portal-web和mis-web的 /api/auth/callback  路由下， 但此路由除了用户登录会跳转之外， 在右上角点击跳转门户或者管理系统时也会走一次，导致用户登录记录不够准确。
在auth服务登录跳转至/api/auth/callback时，判断referer里是否包含AUTH_EXTERNAL_URL + /public/auth区分该跳转来源于登录操作，包含时才记录一次用户登录。

fix(auth): auth登录成功后，重定向回mis和portal时加上一个登录标记

---

.changeset/lazy-zebras-hear.md
apps/mis-server/src/services/job.ts
apps/mis-web/src/i18n/en.ts
apps/mis-web/src/i18n/zh_cn.ts
apps/mis-web/src/pageComponents/job/ChangeJobTimeLimitModal.tsx
apps/mis-web/src/pages/api/job/changeJobTimeLimit.ts
libs/web/src/utils/datetime.ts

**修改作业时限优化**
界面内容及细节优化，增加时间单位选择
修改前（用户ID应为作业ID，国际化项目名称对应错误）
修改后
**BUG修复**
在生产环境中出现了修改作业时限时，同一集群下有两个相同作业id且其中一个状态为已结束，导致修改作业失败
👇
修改作业时限时也需要指定查询作业运行中状态
修改作业时限也采用getJobs接口，并对jobId进行过滤

feat(mis): 修改作业时限优化和BUG修复

---

.changeset/wet-peaches-double.md
README.en.md
README.md

README.md中的二维码无法正常展示
**修改：**
修改二维码的相对路径，不引入仓库名
当前分支可以正常解析路径展示图片

fix(docs): README中二维码没有正常展示

---

apps/mis-server/package.json
apps/mis-server/src/entities/Account.ts
apps/mis-server/src/entities/AccountWhitelist.ts
apps/mis-server/src/entities/JobPriceItem.ts
apps/mis-server/src/entities/StorageQuota.ts
apps/mis-server/src/entities/User.ts
apps/mis-server/src/entities/UserAccount.ts
apps/mis-server/src/utils/orm.ts
apps/mis-server/tests/admin/whitelist.test.ts
apps/mis-server/tests/charging/charging.test.ts
apps/mis-server/tests/init/customStrategy.test.ts
apps/portal-server/tests/file/utils.ts
pnpm-lock.yaml

1. `apps/mis-server/tests/charging/charging.test.ts`的`concurrently pays`中，增加充值记录后查询新增的充值记录的endTime设置为当前时间往后一天，确保能获取到最新的记录
2. 所有关于测试一个Entity中的boolean属性是否为true/false的改为使用`toBeTruthy()`或者`toBeFalsy()`。因为当前配置下修改Entity的boolean属性后，重新读取出来的entity的这个属性为`1`或者`0`。无法重现这个问题。但是由于一般使用boolean字段都是使用是否为truthy值（包括true/1）来使用，一般不会主动判断是否`=== true/false`来使用，所以对业务逻辑影响不大。
3. mis-server的test命令增加`--forceExit`强制退出jest进程，暂时忽略仍有后台线程的情况。
4. （测试无关改动）将deprecated的`IdentifiableReference`改为`Reference`

fix(tests): 修复一些测试问题

---

.changeset/fuzzy-drinks-march.md
.changeset/twenty-phones-warn.md
apps/auth/config/auth.yml
apps/auth/src/auth/bindOtpHtml.ts
apps/auth/src/auth/loginHtml.ts
apps/auth/src/config/auth.ts
apps/auth/src/utils/parseHostname.ts
dev/vagrant/config/auth.yml
docs/docs/deploy/config/auth/config.md

要求 auth 登录界面相关 UI 配置全部修改为可以根据不同域名展示不同内容
auth.yaml，新增 default 和 hostnameMap 配置，当用户没有配置 hostnameMap 或者配置了 hostnameMap 却没有配置对应域名下的相关 ui 配置时采用默认配置
```yaml
ui:
default:
backgroundImagePath: "./assets/background.png"
backgroundFallbackColor: "#8c8c8c"
logo:
scowLogoType: "dark"
customLogoPath: ""
customLogoLink: "https://icode.pku.edu.cn/SCOW/"
slogan:
color: "white"
title: "开源算力中心门户和管理平台"
texts:
- "图形化界面，使用方便"
- "功能丰富，管理简单"
- "一体化部署，开箱即用"
- "标准化平台，支持算力融合"
- "开源中立，独立自主"
footerTextColor: "white"
```

feat(auth): 登录界面UI新增根据不同域名展示不同内容

---

.changeset/few-icons-happen.md
.changeset/mean-donkeys-try.md
apps/auth/src/auth/bindOtpHtml.ts
apps/auth/src/auth/loginHtml.ts
apps/auth/src/utils/getHostname.ts
apps/portal-web/src/pages/_app.tsx
docs/docs/deploy/config/auth/config.md
libs/config/src/ui.ts
libs/web/src/routes/icon/icon.ts
libs/web/src/routes/icon/logo.ts
libs/web/src/utils/getHostname.ts

做了什么：
1、修改web端获取hostname的值，由获取带port的host改为hostname
2、修改auth获取hostname的方式，由从refer中获取改为从header中获取，与mis-web、portal-web保持一致
config/ui.yaml 的参考配置如下
```yaml  title="ui.yaml"
footer:
defaultText: ""
hostnameMap:
183.214.11.32: 183.214.11.32的文本
172.16.20.122: 172.16.20.122的文本
primaryColor:
defaultColor: "#94070A"
hostnameMap:
183.214.11.32: "#0ff"
#'172.16.20.122': "#ff0"
```
效果如下：

fix(web): 修改web端获取hostname的值，由获取带port的host改为hostname

---

.changeset/big-geese-obey.md
apps/auth/src/i18n/en.ts
apps/auth/views/login.liquid
apps/mis-web/src/pages/admin/tenants/create.tsx
apps/mis-web/src/pages/tenant/accounts/create.tsx
apps/mis-web/src/pages/tenant/users/create.tsx
apps/portal-web/src/pageComponents/desktop/NewDesktopTableModal.tsx
apps/portal-web/src/pageComponents/profile/ChangePasswordModal.tsx

fix: 英文label太长和placeholder、文字显示不全

---

libs/protos/scheduler-adapter/package.json

在libs/protos/scheduler-adapter/package.json中显式指定所使用的调度器适配器接口版本

fix: 显式指定所使用的调度器适配器接口版本

---

.changeset/chilly-forks-dress.md
.changeset/sweet-masks-join.md
apps/mis-server/src/services/user.ts
protos/server/user.proto

mis-server中的getAllUsers接口增加email字段，方便其它服务调用scow接口时，获取用户email信息并发送邮件
本地接口测试如下：

fix(mis-server): getAllUsers接口增加email字段

---

.changeset/big-weeks-marry.md
apps/mis-web/src/apis/api.mock.ts
apps/mis-web/src/models/UserSchemaModel.ts
apps/mis-web/src/pageComponents/accounts/AccountTable.tsx
apps/mis-web/src/pageComponents/admin/AllUsersTable.tsx
apps/mis-web/src/pageComponents/tenant/AdminUserTable.tsx

mis-web 中用户列表和账户列表在切换 tab 时会将 tab 作为搜索条件更新数据，从而导致直接从数据统计数量时会出现错误
保存仅按搜索框的条件搜索得到的数据，并从该数据计算每个 tab 的数量

fix(mis-web): 修复 mis-web 中用户和账户列表 tab 数量会随 tab 切换而变化的问题

---

.changeset/lemon-garlics-sin.md
apps/portal-web/src/pageComponents/app/AppSessionsTable.tsx

修改交互式应用列表PENDING状态时不显示剩余时间
修改后👇（本地环境问题，作业id有重复）

feat(portal-web): 交互式应用列表PENDING状态修改为不显示剩余时间

---

apps/portal-web/src/pageComponents/filemanager/RenameModal.tsx

事件冒泡了触发了 table 上绑定的双击事件，将模态框阻止冒泡

fix(portal-web): 文件管理重命名模态框双击触发文件列表双击事件

---

.changeset/tame-crews-boil.md
apps/mis-server/src/services/job.ts
apps/mis-web/src/apis/api.mock.ts
apps/mis-web/src/apis/api.ts
apps/mis-web/src/i18n/en.ts
apps/mis-web/src/i18n/zh_cn.ts
apps/mis-web/src/pageComponents/job/RunningJobTable.tsx
apps/mis-web/src/pages/api/job/cancelJob.ts
protos/server/job.proto

与门户系统类似，新增结束作业操作
与门户系统不同，增加了权限校验：
```typescript
const { job, jobAccessible } = await checkJobAccessible(jobId, cluster, info);
if (jobAccessible === "NotAllowed") {
return { 403: null };
} else if (jobAccessible === "NotFound") {
return { 404: { code: "JOB_NOT_FOUND" } as const };
}
```

feat(mis): 管理系统未结束作业新增结束操作

---

.changeset/purple-cars-worry.md
.changeset/tender-lamps-shout.md
apps/audit-server/src/utils/operationLogs.ts
apps/audit-server/tests/log/operationLogs.test.ts
apps/mis-web/src/components/OperationLogTable.tsx
apps/mis-web/src/pages/api/log/getOperationLog.ts
protos/audit/operation_log.proto

目前操作日志可以根据操作人，操作时间，操作结果以及操作类型进行筛选，但使用过程中，会遇到如下情况， 移除账户操作，需要查看移除a用户的操作，但是存在大量移除账户的操作，根据筛选条件无法快速定位到该条操作记录。
操作日志增加一个筛选框，用户可以输入用户id  账户名等信息对 操作内容中的数据进行模糊搜素

feat(audit): 操作日志内容增加模糊搜索功能

---

.changeset/small-cars-approve.md
apps/cli/assets/config/portal.yaml
apps/portal-web/.eslintrc.json
apps/portal-web/.gitignore
apps/portal-web/config.js
apps/portal-web/package.json
apps/portal-web/scripts/copyMonacoToPublic.js
apps/portal-web/src/i18n/en.ts
apps/portal-web/src/i18n/zh_cn.ts
apps/portal-web/src/pageComponents/filemanager/FileEditModal.tsx
apps/portal-web/src/pageComponents/filemanager/FileManager.tsx
apps/portal-web/src/pageComponents/filemanager/ImagePreviewer.tsx
apps/portal-web/src/utils/config.ts
apps/portal-web/src/utils/languageMap.ts
apps/portal-web/src/utils/nonEditableExtensions.ts
apps/portal-web/src/utils/staticFiles.ts
dev/vagrant/config/portal.yaml
docs/docs/deploy/config/portal/intro.md
libs/config/src/portal.ts
pnpm-lock.yaml
renovate.json

在 `portal.yaml` 中新增配置项：
```yaml
file:
preview:
limitSize: "40m"
edit:
limitSize: "2m"
```
默认可预览文件大小为 50m
默认可编辑文件大小为 1m
目前只有 js、ts、json 等有代码提示，其余语言暂时只有语法高亮

feat(portal-web): 门户系统文件管理新增文件编辑功能

---

.changeset/angry-coats-wait.md
apps/mis-server/src/services/user.ts
apps/mis-web/src/i18n/en.ts
apps/mis-web/src/i18n/zh_cn.ts
apps/mis-web/src/pageComponents/users/UserTable.tsx
apps/mis-web/src/pages/api/users/removeFromAccount.ts

在移出用户的时候，先将用户封锁，保证用户无法提交作业，再查看用户是否有还在运行的作业。如果有的话，提示：用户还有作业在运行，请等待作业结束或手动结束作业后再移出

fix(mis): 移出用户前增加用户是否有运行中作业的判断

---

.changeset/silly-spiders-end.md
apps/mis-web/src/pageComponents/common/PaymentTable.tsx
apps/mis-web/src/pages/accounts/[accountName]/payments.tsx
apps/mis-web/src/pages/admin/finance/payments.tsx
apps/mis-web/src/pages/api/finance/payments.ts
apps/mis-web/src/pages/tenant/finance/accountPayments.tsx
apps/mis-web/src/pages/tenant/finance/payments.tsx

目前充值table为公共组件，一共四个页面使用，分别为
1. 账户管理下的充值记录(仅查用户自己账户的充值信息)
2. 租户管理下的账户充值记录(可查询自己租户下所有的账户充值记录，且可以对账户进行筛选)
3. 租户管理下的租户充值记录(仅查用户自己租户的充值信息)
4. 平台管理下的充值记录(可查询平台所有的租户充值记录，且可以对租户进行筛选)
且查询充值记录共有两个web api： getTenantPayments和 getPayments
getTenantPayments负责4的情况， getPayments负责1，2，3页面
对于getPayments，同时还会传参accountName，searchTenant，再根据这两个参数决定如何调用grpc，前后端一共有多个参数以及if判断来区分这四种情况，逻辑比较乱。
将多余参数删去，仅用searchType 表示四种情况，并且将searchType传至getPayments来判断如何调用grpc服务

chore(mis-web): 优化充值列表以及获取充值记录接口传参

---

.changeset/pretty-pumpkins-enjoy.md
package.json
patches/next@14.0.3.patch
pnpm-lock.yaml

#985 后继。
从next.js 14开始，对已经注册为route的path（包括pages下的页面，pages/api下的api route）发送websocket请求会直接1006断开。代理http/ws请求的path都是一致的/api/proxy，之前/api/proxy是作为api route出现的，所以对/api/proxy的ws请求会直接断开。
此PR删除了next中关于此部分的逻辑，允许了往已经注册为route的path upgrade的逻辑。
此方案在dev可行，在构建后不可行：删除了/api/proxy的api route，在系统启动的时候，为http server增加request事件的handler，在此handler中处理/api/proxy的代理HTTP请求的逻辑。原因推测为构建后会直接404掉没有注册为route的path。

fix(portal-web): 修复/api/proxy无法建立websocket连接

---

.changeset/perfect-dodos-jam.md
.changeset/seven-glasses-rest.md
apps/auth/views/login.liquid
apps/auth/views/otp/bindOtp.liquid
apps/auth/views/otp/qrcode.liquid
apps/cli/assets/install.yaml
apps/cli/src/compose/index.ts
apps/cli/src/config/install.ts
apps/gateway/assets/nginx.conf
apps/gateway/src/env.ts
docs/docs/deploy/config/gateway/config/index.md

修复认证系统的 xss 漏洞和 /api/auth 的 host 头攻击漏洞

fix: 修复安全漏洞

---

.changeset/famous-seals-hunt.md
apps/cli/src/compose/index.ts
apps/cli/src/config/install.ts

Node.js 默认的最大内存限制可能不足以处理高并发量。您可以通过设置 --max-old-space-size 来增加 Node.js 进程的内存限制。
如下图，原本在某环境中，max-old-space-size 默认为 4144，修改install.yaml文件后，成功修改其最大老生代堆内存大小
```yaml title="install.yaml"
misc:
nodeOptions: "--max-old-space-size=8192"
```

feat(cli): install.yaml 文件增加 misc.nodeOptions参数，可设置node服务参数

---

.changeset/calm-ducks-rest.md
apps/portal-server/src/utils/ssh.ts
apps/portal-web/src/pages/api/file/deleteDir.ts

1. 修复 ssh 抛错时 metadata 格式有问题报错 illegal characters
原因是 ssh 操作出问题之后直接将控制台报错当作 metadata 返回，但是控制台报错包含特殊字符与 metadata 要求不符导致了 unknown 的错误。
2. deleteDir 没有 catch 住 internal 错误
3. 限制 ssh 抛错长度
初步判断是问题 3 导致的 portal-web 的 api 部分直接崩溃，限制长度后不会崩溃

fix(portal): 修复用户删除无权限目录时导致的崩溃问题

---

.changeset/empty-dancers-film.md
apps/portal-web/src/i18n/en.ts
apps/portal-web/src/i18n/zh_cn.ts
apps/portal-web/src/pageComponents/filemanager/FileEditModal.tsx

monaco 编辑器会自动判断文件的换行符类型。
1. 如果是新建的空文件，则会根据当前运行环境（例如 windows）来决定换行符。
2. 如果不是空文件会根据当前文件的换行符自动判断后续的换行符，如果是 \r\n 后续也是 \r\n 如果原本就是 \n 那后续也是 \n
提交文件运行的模式下，如果文件换行符为 \r\n 时无法提交成功。
用户在 scow 上编写的时 monaco-editor 可能处于 windows 环境，如果在编辑一个新文件就会导致换行符为 \r\n
所以直接将 monaco-editor 的默认换行符设置为 \n，来避免上述情况的发生。但这样对于原本就是 \r\n 的文件，后续编辑会存在两种换行符。
如果要完全避免文件提交运行报错这个问题，还是应该在提交该文件时将换行符进行切换，这种情况仍然会导致该问题：
1. 用户直接上传的文件的换行符为 \r\n
2. 原本的文件就是 \r\n
如果流式下载文件未结束时直接关闭模态框打开其他文件模态框会有内容覆盖问题，所需要增加中断流式加载

feat(portal-web): 优化文件编辑功能

---

.changeset/eighty-melons-dance.md
apps/portal-web/package.json
pnpm-lock.yaml
renovate.json

@uiw/react-codemirror v4.21.20->v4.21.21 后提交作业页面报错无法打开。暂时未从其更新日志中找到可能导致对应错误的原因，先回退版本

fix: 修复 codemirror 导致的崩溃问题

---

.changeset/unlucky-zebras-design.md
apps/cli/package.json

@sinclair/typebox 升级后 cli 报错：
```
'/**/SCOW/node_modules/.pnpm/@sinclair+typebox@0.32.12/node_modules/@sinclair/typebox/build/require/type/index.js' was not included into executable at compilation stage. Please recompile adding it as asset or script.
```
将 @sinclair/typebox 加入到 pkg 后解决

fix(cli): 添加 @sinclair/typebox 到 pkg

---

.changeset/forty-ducks-hide.md
.changeset/plenty-tools-flash.md
apps/cli/assets/init-full/config/mis.yaml
apps/mis-web/config.js
apps/mis-web/src/pageComponents/job/RunningJobTable.tsx
apps/mis-web/src/pages/api/job/cancelJob.ts
apps/mis-web/src/pages/api/job/changeJobTimeLimit.ts
apps/mis-web/src/pages/api/job/queryJobTimeLimit.ts
apps/mis-web/src/server/jobAccessible.ts
apps/mis-web/src/utils/config.ts
dev/vagrant/config/mis.yaml
libs/config/src/mis.ts

mis 增加配置参数 userChangeJobLimitEnabled 参数控制普通用户是否可以修改作业时限
该参数默认为true， 当改为false时， da'shboard和用户空间处的未结束作业 表里隐藏修改作业时限的按钮，并且api层面也会做该限制。

feat(mis): 增加配置项控制普通用户是否可以修改作业时限

---

.changeset/five-dragons-deliver.md
apps/mis-server/src/entities/StorageQuota.ts
apps/mis-server/src/entities/UserAccount.ts
apps/mis-server/src/migrations/.snapshot-scow_server.json
apps/mis-server/src/migrations/Migration20240129075557.ts

mikro orm 更新到 v6 后运行 migration:create，对数据表有所修改
- 修复了 current_timestamp 对于精度的识别
- mikro orm 将 ManyToOne 的 nullable 默认值修改为了 true，手动改回 false

feat(mis-server): 适配 mikro-orm 更新导致的 Ref nullable 的默认值变化

---

apps/portal-web/src/pageComponents/filemanager/FileManager.tsx

文件管理列表中，path 和 loading 并非同时更新，path 变化后，会有一段时间 loading 仍为 false，即还未触发请求。
故而需要提前设置 loading 状态保证改变 path 马上会触发 loading
待优化: path 变化但数据未更新时，列表的 rowKey 也会发生变化，会触发 react 的 diff，但实际上此时数据未发生变化。

fix(portal-web): 修复连续双击文件名时 path 变化 loading 未变导致进入错误目录

---

.changeset/serious-starfishes-dance.md
libs/server/package.json
pnpm-lock.yaml

如题，目前该包@scow/protos只在dev dependencies引用，无法启动，需要移入dependencies

fix(lib-server):  lib-server @scow/protos 从 devDependencies 移动到 dependencies

---

.changeset/serious-llamas-approve.md
apps/portal-web/src/pages/dashboard.tsx

fix(portal-web): dashboard的监控数据的clusterId

---

.changeset/great-jeans-obey.md
.changeset/late-islands-mate.md
apps/portal-server/src/services/file.ts
apps/portal-web/src/pageComponents/filemanager/ClusterFileTable.tsx
apps/portal-web/src/pages/api/file/list.ts
protos/portal/file.proto

因为文件传输功能需要使用 `touch -a` 更新时间戳来触发 nfs 缓存机制
目前在没有使用文件传输功能时也会在访问文件路径时对其下所有文件使用 `touch -a` ，给后台维护带来不便
此PR修复为只在文件传输功能中对文件执行`touch -a`，同时修复文件名中出现中文字符或特殊字符如";"时 `touch -a` 无法正常执行会在后台打印logger.error的问题
在只进行文件管理下的路径访问时，后台也会出现部分 `touch -a` 的报错
**1.只在文件传输时执行`touch -a`更新访问时间戳**
访问/data/home/demo_admin/前 /data/home/demo_admin/MNIST.ipynb的时间戳
文件管理及提交作业页面选择文件路径时不执行touch -a，不出现touch -a相关报错
/data/home/demo_admin/MNIST.ipynb的时间戳无变化
在文件传输功能时因为/data/home/demo_admin/下某文件路径权限问题touch -a报错
/data/home/demo_admin/MNIST.ipynb的时间戳更新
开发环境文件传输相关功能无异常
**2.特殊字符的情况可以正常执行 `touch -a` 不会在后台留下错误**
时间戳正常更新
**对 #1103 中下述问题进行修复：**
1. 异步会导致ssh提前关闭，无法正常执行`touch -a`， 会一直报错 `unable to exec`
2. 文件切分时切分的是字符串而不是文件数组，导致执行路径出现错误
**针对文件名长度可能引发的错误问题下调每次执行文件数量安全值：**
按一般系统最大命令字节数2097152字节，文件名最长4096字节，下调每一次touch -a执行的文件数量为安全值500

feat(portal): 只在使用文件传输功能时利用touch -a更新时间戳

---

.changeset/blue-ears-provide.md
apps/mis-web/src/pages/api/auth/callback.ts
apps/mis-web/src/stores/UserStore.ts
apps/portal-web/src/pages/api/auth/callback.ts
apps/portal-web/src/stores/UserStore.ts

本 PR 修复两个问题
1. 退出登录时未在 redis 中删除 token 的问题
[#493](https://github.com/PKUHPC/SCOW/pull/493) 中已经提及的 bug，但是修复是无效的，原因是 api 调用是异步的，仍然先执行的后续删除 cookie 操作
2. 修复 token 失效后切换系统时不会返回到登陆系统而是会显示 403 界面的问题

fix(web): 修复 token 失效后切换系统不跳转回登录页面的问题

---

.changeset/wild-paws-drop.md
apps/cli/assets/init-full/config/mis.yaml
apps/cli/assets/init/config/mis.yaml
deploy/vagrant/scow/scow-deployment/config/mis.yaml
docs/blog/2023-10-20-scow-update1.0.md
docs/docs/deploy/config/mis/intro.md

mis.yaml 原本获取作业的cron表达式：    
```mis.yaml
cron: "10 */10 * * * *"
```
前面多了一个10，默认应该是10分钟一次：*/10 * * * *，前面多加一个10会将定时任务设置在每10分的第10秒精确执行，其实也是不影响我们想要的效果。但为了让部分熟悉linux的用户理解更准确，我们去掉最前面的10，修改后如下：
```mis.yaml
cron: "*/10 * * * *"
```

fix(cli): 去掉 node-cron 表达式前秒的限制

---

.changeset/kind-nails-hunt.md
protos/portal/file.proto

该 pr 为 [#937](https://github.com/PKUHPC/SCOW/pull/937/files) 遗漏部分的补充修改
uint32 能表示的文件大小约为 4GB，故改为 uint64。
需要注意，scow 目前 proto 对于 uint64 转译后生成的文件中被解释为 number。number 比 uint64 的数值表示范围要小很多，目前没出现问题是由于 number 可以表示约为 9 PB 的文件大小，一般不会出现不够的情况

fix(portal): 修改 GetFileMetadataResponse 中文件大小 size 为 uint64

---

.changeset/cuddly-frogs-rest.md
apps/ai/src/app/(auth)/image/CreateEditImageModal.tsx
apps/ai/src/server/trpc/route/image/image.ts
apps/ai/src/server/utils/image.ts

**改动**
1.此pr在` containerd `运行时的 `nerdctl push `命令中追加 `--all-platforms`运行参数，避免可能由于基础镜像为多平台的大镜像在推送到镜像仓库中推送失败的问题
2.在创建镜像与编辑镜像时追加后台详细错误信息展示
**修改后**
1.不影响docker运行时的命令执行，本地创建和远程镜像创建均可成功
2.不影响containerd运行时普通镜像上传，本地创建和远程镜像创建均可成功
3.创建后本地拉取及制作的镜像正常删除
4.创建/编辑时错误信息补充完整

fix(ai): Containerd运行时下大镜像推送失败

---

.changeset/tasty-beers-grow.md
apps/portal-web/src/pageComponents/dashboard/EntryItem.tsx

fix(portal-web): 快捷方式的icon显示大小问题

---

renovate.json

react-query有v5更新，但是trpc需要等到11版本发布后才能兼容react-query v5。暂时停止react-query更新直到trpc v11发布。

chore:  暂停react-query更新

---

.github/workflows/docs-preview.yaml
.github/workflows/docs.yaml
.github/workflows/pr-cleanup.yaml
.github/workflows/side-projects.yaml
.github/workflows/test-build-publish.yaml

1. 文档中SCOW镜像地址以实际仓库为准
2. scow-vagrant发布仓库可通过仓库的secret配置
3. 将会在所有arm-开头的仓库中构建arm镜像

chore: 更新CI配置

---

dev/test-adapter/Dockerfile
docker/Dockerfile.docs
docker/Dockerfile.scow

pnpm的最新版升级到了9.0，Lockfile版本从6.x更新到了9.x，存在不兼容问题。而现在在容器构建时，执行`pnpm fetch`时下载的pnpm为最新版，而不是package.json中执行的版本，使得在执行pnpm fetch时lockfile被更新到最新的9.x版本，但是后面在执行后续的pnpm指令时使用的pnpm版本为老版本，不兼容最新的lockfile。
由于 https://github.com/vercel/turbo/issues/7993 问题，现在不能升级pnpm到最新的9.0版本。
此PR把package.json在执行`pnpm fetch`执行复制进了容器，使得执行`pnpm fetch`时所使用的pnpm版本为指定的版本而非最新版，保证lockfile不会意外改变。

fix(ci): 修改pnpm最新版升级到9.0造成的构建问题

---

.changeset/serious-fishes-bathe.md
apps/ai/next.config.mjs
apps/ai/package.json

启用AI项目的服务器端代码优化serverMinification，只使用`--no-mangling`和`swcMinify: false`来关闭name mangling以解决[这个问题](https://github.com/mikro-orm/mikro-orm/issues/5487)。理论上来说应该只要`--no-mangling`就行，但是应该还是next的bug （ https://github.com/vercel/next.js/issues/50208 ），必须还要同时设置`swcMinify: false`才可以。

fix(ai): 启用serverMinification，使用--no-mangling

---

.github/workflows/test-build-publish.yaml

目前由于ifaxity/wait-on-action 仓库发布了1.2.0版本 会遇到 报错 https://github.com/iFaxity/wait-on-action/issues/23， 故暂时将该仓库固定在v1.1.0版本保证scow的ci正常跑通

chore: 固定 github workflow 中 ifaxity/wait-on-action的版本

---

.changeset/healthy-cycles-sin.md
.github/workflows/test-build-publish.yaml
apps/ai/src/app/(auth)/algorithm/AlgorithmTable.tsx
apps/ai/src/app/(auth)/algorithm/AlgorithmVersionList.tsx
apps/ai/src/app/(auth)/dataset/DatasetListTable.tsx
apps/ai/src/app/(auth)/dataset/DatasetVersionList.tsx
apps/ai/src/app/(auth)/image/ImageListTable.tsx
apps/ai/src/app/(auth)/jobs/[clusterId]/AppSessionsTable.tsx
apps/ai/src/app/(auth)/jobs/[clusterId]/LaunchAppForm.tsx
apps/ai/src/app/(auth)/jobs/[clusterId]/hooks.ts
apps/ai/src/app/(auth)/model/ModelTable.tsx
apps/ai/src/app/(auth)/model/ModelVersionList.tsx
apps/ai/src/server/trpc/route/algorithm/algorithm.ts
apps/ai/src/server/trpc/route/algorithm/algorithmVersion.ts
apps/ai/src/server/trpc/route/auth.ts
apps/ai/src/server/trpc/route/dataset/dataset.ts
apps/ai/src/server/trpc/route/dataset/datasetVersion.ts
apps/ai/src/server/trpc/route/image/image.ts
apps/ai/src/server/trpc/route/jobs/apps.ts
apps/ai/src/server/trpc/route/model/model.ts
apps/ai/src/server/trpc/route/model/modelVersion.ts
apps/ai/src/server/trpc/route/utils.ts
apps/ai/src/utils/parse.ts

trpc openapi 对于get请求，处理boolean参数时会将true和false都识别为字符串后 以true的逻辑调用
将Get请求 input 里的`z.boolean()` ->```
z.union([z.literal("true"), z.literal("false")]).transform((arg) =>arg === "true"); ```，可以使trpc-openapi正确处理input里的boolean参数

fix(ai):  修复 trpc openapi 将 boolean params 全部转为 string 的问题

---

.changeset/violet-deers-sniff.md
docs/docs/integration/scow-api-hook/hook.md
libs/config/src/common.ts
libs/hook/src/index.ts

feat(hook): 支持配置多个Hook

---

.changeset/grumpy-spoons-guess.md
apps/ai/src/app/(auth)/jobShell/[clusterId]/[jobId]/page.tsx
apps/portal-web/package.json
apps/portal-web/src/pageComponents/shell/Shell.tsx
apps/portal-web/src/pages/shell/[cluster]/[loginNode]/[[...path]].tsx
pnpm-lock.yaml

The npm package `xterm` has been renamed to `@xterm/xterm`, and `xterm-addon-fit` has been renamed to `@xterm/addon-fit`.
This change has resulted in the automatic update of these dependencies not working. I renamed these two packages in portal-web's package.json and conducted a test.

feat(web): xterm npm 包更名，修改导入

---

.changeset/spotty-wombats-impress.md
apps/ai/src/app/(auth)/layout.tsx
apps/mis-web/src/i18n/en.ts
apps/mis-web/src/i18n/zh_cn.ts
apps/portal-web/src/pageComponents/dashboard/OverviewTable.tsx

1.做了什么
portal中使用率颜色会根据数字大小发生变化，并且保留两位小数
2.
mis中导航栏HPC->超算平台
**此PR原本是#1238中的内容，但是根据李老师要求，从#1238独立出来**

feat(portal): 修改了portal中部分UI样式

---

apps/mis-server/src/services/charging.ts

fix(mis): 修复消费记录为空时报错

---

apps/mis-web/src/pageComponents/finance/ChargeTable.tsx

fix(mis): 账户消费记录扣费记录改回精度为2

---

.changeset/nasty-islands-type.md
apps/cli/package.json
apps/cli/src/cmd/updateCli.ts
pnpm-lock.yaml

**在 #1251 中，octokit发生大版本更新导致octokit的导入出现问题, 通过require导入也无法解决**
https://github.com/octokit/octokit.js/pull/2674
**octokit/core等不支持octokit.rest方法**
**此PR指定依赖为 @octokit/rest 进行修复**
**修复后可正常运行cli命令**

fix(cli): 修复 octokit 依赖更新导致 cli 命令执行失败的问题

---

.changeset/sixty-taxis-shave.md
apps/ai/src/components/AccountSelector.tsx
apps/mis-web/src/pageComponents/finance/AccountMultiSelector.tsx
apps/mis-web/src/pageComponents/finance/AccountSelector.tsx
apps/mis-web/src/pageComponents/tenant/TenantSelector.tsx
apps/mis-web/src/pages/tenant/storage.tsx
apps/portal-web/src/components/InputGroupFormItem.tsx
apps/portal-web/src/pageComponents/job/AccountListSelector.tsx
apps/portal-web/src/pageComponents/job/AccountSelector.tsx
apps/portal-web/src/pageComponents/job/PartitionSelector.tsx
apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx

1.6.1发版测试发现UI故障：
定位后antd回复：Input.group已经废弃，因此使用 Space.Compact
https://github.com/ant-design/ant-design/issues/49607
mis：
1.账户消费记录、充值记录中的账户多选框
2.平台管理、租户充值记录、租户选择框
portal:
1.提交作业、应用的最长时间输入框、分区选择框
ai:
1.账户选择框

refactor(web): 所有Input.Group compact组件替换成Space.Compact

---

dev/ldap/Dockerfile

https://serverfault.com/questions/1161816/mirrorlist-centos-org-no-longer-resolve
CentOS 7在2024年7月1日EOL了，默认的mirrors.centos.org的包镜像地址消失了，测试用的LDAP镜像使用的CentOS7无法安装包了。本PR根据上面的链接使用vault.centos.org地址作为centos 7的包镜像地址。

chore: 修复centos7包管理镜像地址

---

.changeset/chilled-schools-pull.md
apps/mis-web/src/apis/api.mock.ts
apps/mis-web/src/apis/api.ts
apps/mis-web/src/pages/_app.tsx
apps/mis-web/src/pages/api/admin/getClustersRuntimeInfo.ts
apps/mis-web/src/pages/api/simpleClustersInfo.ts
apps/mis-web/src/stores/ClusterInfoStore.ts
apps/mis-web/src/utils/cluster.ts
libs/config/src/cluster.ts
libs/ssh/src/ssh.ts
libs/web/src/utils/cluster.ts

因初始化时无法通过token或auth鉴权，导致系统初始化时的可用集群查询结果为空
在管理系统的web端原有获取集群配置信息接口以外增加返回简单集群信息的web接口 `getSimpleClustersInfoFromConfigFiles`
返回信息仅包含 `clusterId, displayName,` 及用于优先级排序的 `priority`
在`getSimpleClustersInfoFromConfigFiles` 及获取当前集群在线信息接口中` getClustersRuntimeInfo` 增加是否已初始化判断，未初始化时允许所有人获取简单集群在线信息
系统初始化时获取集群信息正常，各操作正常，初始化完成后登录正常

fix(mis): 系统初始化时可用集群报错

---

.changeset/khaki-cheetahs-warn.md
apps/portal-server/src/utils/scowd.ts
libs/utils/src/url.ts

scow 在获取 scowdClient 时是通过 login 的地址拼接对应 scowd  的 port 的方式获得的 scowd 的完整地址。之前未考虑到 login地址中可能会带上端口，拼接的时候就会出错。所以本次修复主要是移除 login 地址中的端口号再进行拼接

fix(portal-server): 修复获取 scowdClient 时拼接地址的错误

---

apps/ai/src/server/trpc/route/jobs/apps.ts
apps/ai/src/server/utils/schedulerAdapterUtils.ts

因为适配器接口版本已分开，以后可能因为接口增加或变更使client类型已不再一致， 会出现报错
在`listAppSessions`, `checkAppConnectivity`, `connectToApp` 三个使用了公共接口的地方，页面表现与当前主分支表现一致

fix(ai): 区分SCOW和SCOW AI使用的有关适配器请求的公共逻辑函数

---

.changeset/ninety-zoos-think.md
.changeset/shaggy-maps-hunt.md
apps/mis-server/config/mis.yaml
apps/mis-server/src/app.ts
apps/mis-server/src/plugins/syncBlockStatus.ts
apps/mis-server/src/services/admin.ts
apps/mis-server/tests/admin/updateBlockStatus.test.ts
apps/mis-web/src/i18n/en.ts
apps/mis-web/src/i18n/zh_cn.ts
apps/mis-web/src/pages/admin/systemDebug/slurmBlockStatus.tsx
apps/mis-web/src/pages/api/admin/synchronize/syncBlockStatus.ts
protos/server/admin.proto

mis-server启动时，不完整同步一次封锁状态，而是只在后台运行，以减少mis-server启动时间。
UI和API修改：
- `AdminService.UpdateBlockStatus` API行为改变：当调用API时后台正在进行一次同步，那么调用此API会返回`ALREADY_EXISTS`
- UI上，当用户手动点击同步封锁状态时，如果后台正在进行一次同步，那么会报错

fix(mis): mis-server启动时，不完整同步一次封锁状态

---

.changeset/strange-lemons-notice.md
apps/ai/src/app/clientLayout.tsx

feat: ai加上国际化的Provider

---

.changeset/slow-falcons-give.md
apps/portal-server/src/clusterops/app.ts
libs/protos/scowd/protos/api/application/app.proto
libs/scowd/src/client.ts

新增 scowd app service 和 GetAppLastSubmission 接口，并实现其在 scow 中的调用
由于目前只实现这一个接口，所以没有将 app service 中 ssh 和 scowd 像文件服务和桌面服务那样完全区分开
scowd 实现：https://github.com/PKUHPC/SCOWD/pull/11

feat(portal-server): 新增 scowd GetAppLastSubmission 接口及其在 scow 中的调用

---

.changeset/nice-baboons-give.md
apps/cli/assets/init-full/install.yaml
apps/cli/src/compose/index.ts
apps/cli/src/config/install.ts

close https://github.com/PKUHPC/SCOW/issues/1421 and https://github.com/PKUHPC/SCOW/issues/1423

feat: new install options: sshDir and extraEnvs

---

.changeset/luminous-owl-update.md
docs/docs/deploy/config/portal/apps/configure-attributes.md

修改文档中记载的属性名，由 default 修改为 defaultValue
已确认其他关于交互式应用HTML表单配置的地方没有此属性名称错误

fix(docs): 修改交互式应用HTML表单默认值配置名为defaultValue

---

.changeset/silent-tomatoes-attend.md
docker/entrypoint.sh
docs/docs/info/mis/business/billing.mdx

修复某次升级导致`./cli compose run {container} {args}`中arg没有传递给容器的问题

fix(cli): 修复./cli compose run {container} {args}中arg没有传递给容器的问题
